///////////////////////////////////////////////////////////////////////////////
// Unit tests for ABC News scripts, partially generated by Github Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// streamline.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('streamline.js', () => {

    let workingSpace;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {
        // clear persistent values
        GM_clearValues();

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);

        // element identified by id
        const elementById = document.createElement('div');
        elementById.id = 'testElement';
        workingSpace.appendChild(elementById);

        // elements identified by class
        const elementsByClass = [
            document.createElement('div'),
            document.createElement('div')
        ];
        for (let e of elementsByClass) {
            e.className = 'testClass';
            workingSpace.appendChild(e);
        }

        // element identified by H2 heading test
        const headingContainer = mockRailElement('testHeadingContainer', 'abc123', 'Test Heading');
        workingSpace.appendChild(headingContainer);

        // mock rail element
        const railContainer = mockRailElement('railContainer', 'abc123');
        workingSpace.appendChild(railContainer);

    });


    afterEach(() => {
        // remove the working space and spy
        document.body.removeChild(workingSpace);
    });


    describe('applyConfiguration', () => {

        let elementById;
        let elementByClass;
        let elementByHeading;
        let errorSpy;
        let applyRendererSpy;
        let renderExpandableSpy;
        let renderHiddenSpy;

        beforeEach(() => {

            // get references to the test elements
            elementById = workingSpace.querySelector('#testElement');
            elementByClass = workingSpace.querySelector('.testClass');
            elementByHeading = workingSpace.querySelector('#testHeadingContainer .Rail_root__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');

            // spy on rendering functions
            applyRendererSpy = spyOn(this, 'applyRenderer').and.callThrough();
            renderExpandableSpy = spyOn(this, 'renderExpandable');
            renderHiddenSpy = spyOn(this, 'renderHidden');
        });

        it('applies configuration without saving', () => {
            const mockConfNoSave = {
                '#testElement': 'default',
                '.testClass': 'expanded',
                'Test Heading': 'compressed'
            };
            applyConfiguration(mockConfNoSave);
            expect(applyRendererSpy).toHaveBeenCalledTimes(2);
            expect(applyRendererSpy).not.toHaveBeenCalledWith('#testElement', jasmine.any(Function));
            expect(applyRendererSpy).toHaveBeenCalledWith('.testClass', jasmine.any(Function));
            expect(applyRendererSpy).toHaveBeenCalledWith('Test Heading', jasmine.any(Function));
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByClass, false, null);
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByHeading, true, null);
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('applies configuration with saving', () => {
            GM_setValue('.testClass', 'compressed');
            const mockConfWithSave = {
                '#testElement': 'hidden',
                '.testClass': 'saved',
                'Test Heading': 'saved'
            };
            applyConfiguration(mockConfWithSave);
            expect(applyRendererSpy).toHaveBeenCalledTimes(3);
            expect(renderHiddenSpy).toHaveBeenCalledWith(elementById);
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByClass, true, '.testClass');
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByHeading, false, 'Test Heading');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event for an invalid configuration value', () => {
            const mockConfBadValue = { '#testElement': 'badValue' };
            applyConfiguration(mockConfBadValue);
            expect(applyRendererSpy).not.toHaveBeenCalled();
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

    });

    describe('applyRenderer', () => {

        // mock rendering function
        function mockRender(target) {
            if (target != null) {
                target.setAttribute('data-rendered', 'true');
            }
        };

        let elementById;
        let elementsByClass;
        let elementByHeading;
        let errorSpy;

        beforeEach(() => {
            // get references to the test elements
            elementById = document.getElementById('testElement');
            elementsByClass = document.getElementsByClassName('testClass');
            elementByHeading = workingSpace.querySelector('#testHeadingContainer .Rail_root__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');
        });

        it('logs unexpected events for invalid configuration keys', () => {
            applyRenderer('', mockRender);
            applyRenderer('#', mockRender);
            applyRenderer('.', mockRender);
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).toHaveBeenCalledTimes(3);
        });

        it('renders elements identified by id', () => {
            applyRenderer('#testElement', mockRender);
            expect(elementById.getAttribute('data-rendered')).toBe('true');
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            elementById.removeAttribute('data-rendered');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('renders elements identified by class', () => {
            applyRenderer('.testClass', mockRender);
            for (let e of elementsByClass) {
                expect(e.getAttribute('data-rendered')).toBe('true');
                e.removeAttribute('data-rendered');
            }
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('renders elements identified by H2 heading text', () => {
            applyRenderer('Test Heading', mockRender);
            expect(elementByHeading.getAttribute('data-rendered')).toBe('true');
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event for an unmatched configuration key', () => {
            applyRenderer('Garbage', mockRender);
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

        it('logs an unexpected event for a missing rail root', () => {
            findRailRoot(elementByHeading).remove();
            applyRenderer('Test Heading', mockRender);
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

    });

    it('cleanStoredValues', () => {

        // mock some stored values
        GM_setValue('savedExpanded', 'expanded');
        GM_setValue('savedCompressed', 'compressed');
        GM_setValue('unsavedExpanded', 'expanded');
        GM_setValue('unsavedCompressed', 'compressed');
        GM_setValue('deprecatedComponent', 'compressed');

        // mock configuration
        const mockConf = {
            'savedExpanded': 'saved',
            'savedCompressed': 'saved',
            'unsavedExpanded': 'expanded',
            'unsavedCompressed': 'compressed'
        };
        cleanStoredValues(mockConf);

        // configuration for saved components should be unaffected
        expect(GM_getValue('savedExpanded', null)).toBe('expanded');
        expect(GM_getValue('savedCompressed', null)).toBe('compressed');

        // configuration for no-longer-saved components should be removed
        expect(GM_getValue('unsavedExpanded', null)).toBeNull();
        expect(GM_getValue('unsavedCompressed', null)).toBeNull();

        // configuration for deprecated components should be removed
        expect(GM_getValue('deprecatedComponent', null)).toBeNull();

    });

    it('findRailRoot', () => {

        // check finding the root without any search
        const railRoot = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
        const trivialRailRoot = findRailRoot(railRoot);
        expect(trivialRailRoot).toBe(railRoot);

        // check searching downwards
        const railContainer = document.getElementById('railContainer');
        const downwardsRailRoot = findRailRoot(railContainer);
        expect(downwardsRailRoot).toBe(railRoot);

        // check searching upwards
        const railChild = railRoot.firstElementChild;
        const upwardsRailRoot = findRailRoot(railChild);
        expect(upwardsRailRoot).toBe(railRoot);

        // return null when no rail root exists in the tree
        const testElement = document.getElementById('testElement');
        const nullRailRoot = findRailRoot(testElement);
        expect(nullRailRoot).toBeNull();

    });

    it('logUnexpectedEvent', () => {

        // spy on console.warn()
        const consoleSpy = new spyOn(console, 'warn');

        // valid source identifiers should invoke console.warn()
        logUnexpectedEvent("conf", "Conf error.");
        expect(consoleSpy).toHaveBeenCalledWith("Configuration error: Conf error.");
        logUnexpectedEvent("dom", "DOM error.");
        expect(consoleSpy).toHaveBeenCalledWith("Possible DOM change: DOM error.");

        // invalid source identifier should report an error
        logUnexpectedEvent("invalid", "Invalid source.");
        expect(consoleSpy).toHaveBeenCalledWith("logUnexpectedEvent called with invalid source: Invalid source.");

    });

    it('onClickExpandable', () => {

        // get references to the test elements
        const root = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
        const header = workingSpace.querySelector('#railContainer .Rail_header__abc123')
        const content = workingSpace.querySelector('#railContainer .Rail_content__abc123');

        // clicking on the default header hides content and makes the cursor zoom-in, without saving
        onClickExpandable(header, content, null);
        expect(content.style.display).toBe('none');
        expect(header.style.cursor).toBe('zoom-in');
        expect(GM_getValue('testExpandable', null)).toBeNull();

        // clicking on a compressed header makes content visible and cursor zoom-out
        onClickExpandable(header, content, null);
        expect(content.style.display).toBe('block');
        expect(header.style.cursor).toBe('zoom-out');
        expect(GM_getValue('testExpandable', null)).toBeNull();

        // clicking again hides the content; this time save the result
        onClickExpandable(header, content, 'testExpandable');
        expect(content.style.display).toBe('none');
        expect(header.style.cursor).toBe('zoom-in');
        expect(GM_getValue('testExpandable', null)).toBe('compressed');

        // clicking again make the content visible; this time saving the result
        onClickExpandable(header, content, 'testExpandable');
        expect(content.style.display).toBe('block');
        expect(header.style.cursor).toBe('zoom-out');
        expect(GM_getValue('testExpandable', null)).toBe('expanded');

    });


    describe('renderExpandable', () => {

        let root;
        let header;
        let content;
        let errorSpy;

        beforeEach(() => {
            // get references to the test elements
            root = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
            header = workingSpace.querySelector('#railContainer .Rail_header__abc123')
            content = workingSpace.querySelector('#railContainer .Rail_content__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');
        });

        it('content is visible when startCompressed is not supplied', () => {
            renderExpandable(root);
            expect(content.style.display).not.toBe('none');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('content is visible and cursor is zoom-out when startCompressed is false', () => {
            renderExpandable(root, false);
            expect(content.style.display).not.toBe('none');
            expect(header.style.cursor).toBe('zoom-out');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it ('content is compressed and cursor is zoom-in when startCompressed is true', () => {
            renderExpandable(root, true);
            expect(content.style.display).toBe('none');
            expect(header.style.cursor).toBe('zoom-in');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('clicking invokes onClickExpandable with correct arguments', () => {
            const clickSpy = spyOn(this, 'onClickExpandable');
            renderExpandable(root, true);
            header.click();
            expect(clickSpy).toHaveBeenCalledTimes(1);
            expect(clickSpy).toHaveBeenCalledWith(header, content, null);
            renderExpandable(root, true, 'testExpandable');
            header.click();
            expect(clickSpy).toHaveBeenCalledTimes(2);
            expect(clickSpy).toHaveBeenCalledWith(header, content, 'testExpandable');
        });

        it('mouseover sets header background; mouseout resets it', () => {
            renderExpandable(root, false);
            const originalBackgroundColor = header.style.backgroundColor;
            header.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
            expect(header.style.backgroundColor).toBe('var(--nw-colour-theme-surface-tint)');
            header.dispatchEvent(new MouseEvent('mouseout', { bubbles: true }));
            expect(header.style.backgroundColor).toBe(originalBackgroundColor);
        });

        it('logs an unexpected event for an element with no rail root', () => {
            const testElement = document.getElementById('testElement');
            renderExpandable(testElement, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

        it('logs an unexpected event for a rail element with no content', () => {
            content.remove();
            renderExpandable(root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

        it('log an unexpected event for a rail element with no header', () => {
            header.remove();
            renderExpandable(root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

    });


    it('renderHidden', () => {

        // check single element
        const testElement = document.getElementById('testElement');
        testElement.style.display = 'block';
        renderHidden(testElement);
        expect(testElement.style.display).toBe('none');

        // check rail element
        const railContainer = document.getElementById('railContainer');
        const railRoot = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
        const railChild = railRoot.firstElementChild;
        renderHidden(railRoot);
        expect(railRoot.style.display).toBe('none');
        expect(railContainer.style.display).not.toBe('none');
        expect(railChild.style.display).not.toBe('none');

    });

});


// Mock up a rail element. See streamline.renderExpandable() for the structure
// of a rail element.
//
// Input:
//   id (string) - an id for the containing div
//   nonce (string) - an arbitrary string to append to class names
//   title (string) - the text content of the header
//
// Returns: a div containing a rail element in the format used by the ABC site
function mockRailElement(id, nonce, title = null) {

    // containing div
    const container = document.createElement('div');
    container.id = id;

    // rail root
    const root = document.createElement('div');
    root.className = 'Rail_root__' + nonce + ' Rail_sideScrolling__' + nonce;
    container.appendChild(root);

    // rail header
    const header = document.createElement('div');
    header.className = 'Rail_header__' + nonce;
    root.appendChild(header);
    if (title != null) {
        const headerContent = document.createElement('h2');
        headerContent.textContent = title;
        header.append(headerContent);
    }

    // scrolling window
    const navigation = document.createElement('div');
    navigation.className = 'Rail_scollNavigation__' + nonce;
    root.appendChild(navigation);

    // content
    const content = document.createElement('div');
    content.className = 'Rail_content__' + nonce;
    root.appendChild(content);

    return container;

}
