///////////////////////////////////////////////////////////////////////////////
// Unit tests for ABC News scripts, partially generated by Github Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// streamline.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('streamline.js', () => {

    let workingSpace;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {
        // clear persistent values
        GM_clearValues();

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);

        // element identified by id
        const elementById = document.createElement('div');
        elementById.id = 'testElement';
        workingSpace.appendChild(elementById);

        // elements identified by class
        const elementsByClass = [
            document.createElement('div'),
            document.createElement('div')
        ];
        for (let e of elementsByClass) {
            e.className = 'testClass';
            workingSpace.appendChild(e);
        }

        // element identified by H2 heading test
        const headingContainer = mockRailElement('testHeadingContainer', 'abc123', 'Test Heading', false);
        workingSpace.appendChild(headingContainer);

        // mock in-body rail element
        const railContainer = mockRailElement('railContainer', 'abc123', 'In-body rail', false);
        workingSpace.appendChild(railContainer);

        // mock sidebar rail element
        const railSidebar = mockRailElement('railSidebar', 'abc123', 'Sidebar Rail', true);
        workingSpace.appendChild(railSidebar);

        // mock article summary
        const articleSummary = document.createElement('div');
        articleSummary.id = 'articleSummary';
        articleSummary.innerHTML = '<div class="ArticleSummary_summary__abc123">' +
            '<div class="Article_main__abc123">' + '<h2>In Short</h2>' +
            '<p>Paragraph 1</p><p>Paragraph 2</p><p>Paragraph 3</p>' +
            '</div></div>';
        workingSpace.appendChild(articleSummary);

        // mock contact form
        const zendeskForm = document.createElement('div');
        zendeskForm.id = 'zendeskForm';
        zendeskForm.innerHTML = '<div class="ZendeskForm_zendeskForm__abc123">' +
            '<div data-component="ZendeskFormUI">' + '<h3>Contact ...</h3>' +
            '<form><input type="text" name="zendeskInput"></input></form>' +
            '</div></div>';
        workingSpace.appendChild(zendeskForm);

        // mock the top stories panel in the footer
        const topStoriesFooter = document.createElement('div');
        topStoriesFooter.id = 'topStoriesFooter';
        topStoriesFooter.innerHTML = '<div class="TopStories_container__abc123">' +
            '<header class="SectionHeader_header__4_bXM TopStories_collectionHeading__abc123">'
            '<div class="SectionHeader_mainSectionHeader___abc123">' + '<h2>Top Stories</h2>' +
            '</div></header>' +
            '<ol class="TopStories_list__abc123"><li>Story 1</li></ol>' +
            '</div></div>';
        workingSpace.appendChild(topStoriesFooter);

        // mock sidebar element with H2 title
        const asideWithH2 = document.createElement('aside');
        asideWithH2.id = 'asideWithH2';
        asideWithH2.className = 'Article_aside__abc123';
        asideWithH2.innerHTML = '<div data-component="ArticleAside">' +
            '<h2 class="ArticleAside_title__abc123">Aside title</h2>' +
            '<ul><li>Aside1</li><li>Aside2</li></ul>' +
            '</div>';
        workingSpace.appendChild(asideWithH2);

        // mock sidebar element with rail header
        const asideWithRailHeader = document.createElement('div');
        asideWithRailHeader.id = 'asideWithRailHeader';
        asideWithRailHeader.className = 'Home_aside1__abc123';
        asideWithRailHeader.innerHTML = '<div class="Rail_header__abc123">Header</div>' +
            '<div>Content 1</div>' + '<div>Content 2</div>';
        workingSpace.appendChild(asideWithRailHeader);

        // mock in-article panel
        const inArticlePanel = document.createElement('div');
        inArticlePanel.id = 'inArticlePanel';
        inArticlePanel.className = 'Panel_root__abc123';
        inArticlePanel.innerHTML = '<div class="Panel_content__abc123">' +
            '<div class="Rail_header__abc123"><h2>Title</h2><div>Subtitle</div></div>' +
            '<div>Panel contents</div></div>';
         workingSpace.appendChild(inArticlePanel);

    });


    afterEach(() => {
        // remove the working space
        document.body.removeChild(workingSpace);
    });


    describe('applyConfiguration', () => {

        let elementById;
        let elementByClass;
        let elementByHeading;
        let errorSpy;
        let applyRendererSpy;
        let renderExpandableSpy;
        let renderHiddenSpy;

        beforeEach(() => {

            // get references to the test elements
            elementById = workingSpace.querySelector('#testElement');
            elementByClass = workingSpace.querySelector('.testClass');
            elementByHeading = workingSpace.querySelector('#testHeadingContainer .Rail_root__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');

            // spy on rendering functions
            applyRendererSpy = spyOn(this, 'applyRenderer').and.callThrough();
            renderExpandableSpy = spyOn(this, 'renderExpandable');
            renderHiddenSpy = spyOn(this, 'renderHidden');
        });

        it('applies configuration without saving', () => {
            const mockConfNoSave = {
                '#testElement': 'default',
                '.testClass': 'expanded',
                'Test Heading': 'compressed'
            };
            applyConfiguration("test", mockConfNoSave);
            expect(applyRendererSpy).toHaveBeenCalledTimes(2);
            expect(applyRendererSpy).not.toHaveBeenCalledWith('#testElement', jasmine.any(Function));
            expect(applyRendererSpy).toHaveBeenCalledWith('.testClass', jasmine.any(Function));
            expect(applyRendererSpy).toHaveBeenCalledWith('Test Heading', jasmine.any(Function));
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByClass, false, null);
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByHeading, true, null);
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('applies configuration with saving', () => {
            GM_setValue(storageKey('test', '.testClass'), 'compressed');
            const mockConfWithSave = {
                '#testElement': 'hidden',
                '.testClass': 'saved',
                'Test Heading': 'saved'
            };
            applyConfiguration("test", mockConfWithSave);
            expect(applyRendererSpy).toHaveBeenCalledTimes(3);
            expect(renderHiddenSpy).toHaveBeenCalledWith(elementById);
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByClass, true, storageKey('test', '.testClass'));
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByHeading, false, storageKey('test', 'Test Heading'));
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event for an invalid configuration value', () => {
            const mockConfBadValue = { '#testElement': 'badValue' };
            applyConfiguration("test", mockConfBadValue);
            expect(applyRendererSpy).not.toHaveBeenCalled();
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

    });

    describe('applyRenderer', () => {

        // mock rendering function
        function mockRender(target) {
            if (target != null) {
                target.setAttribute('data-rendered', 'true');
            }
        };

        let elementById;
        let elementsByClass;
        let elementByHeading;
        let errorSpy;

        beforeEach(() => {
            // get references to the test elements
            elementById = document.getElementById('testElement');
            elementsByClass = document.getElementsByClassName('testClass');
            elementByHeading = workingSpace.querySelector('#testHeadingContainer .Rail_root__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');
        });

        it('logs unexpected events for invalid configuration keys', () => {
            applyRenderer('', mockRender);
            applyRenderer('#', mockRender);
            applyRenderer('.', mockRender);
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).toHaveBeenCalledTimes(3);
        });

        it('renders elements identified by id', () => {
            applyRenderer('#testElement', mockRender);
            expect(elementById.getAttribute('data-rendered')).toBe('true');
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            elementById.removeAttribute('data-rendered');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('renders elements identified by class', () => {
            applyRenderer('.testClass', mockRender);
            for (let e of elementsByClass) {
                expect(e.getAttribute('data-rendered')).toBe('true');
                e.removeAttribute('data-rendered');
            }
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('renders elements identified by H2 heading text', () => {
            applyRenderer('Test Heading', mockRender);
            expect(elementByHeading.getAttribute('data-rendered')).toBe('true');
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event for an unmatched configuration key', () => {
            applyRenderer('Garbage', mockRender);
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

        it('logs an unexpected event for a missing rail root', () => {
            elementByHeading.remove();
            applyRenderer('Test Heading', mockRender);
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

    });

    describe('cleanStoredValues', () => {

        // mock configuration
        const mockConf = {
            'savedExpanded': 'saved',
            'savedCompressed': 'saved',
            'unsavedExpanded': 'expanded',
            'unsavedCompressed': 'compressed'
        };

        beforeEach(() => {

            // mock some stored values
            GM_setValue(storageKey('article', 'savedExpanded'), 'expanded');
            GM_setValue(storageKey('article', 'savedCompressed'), 'compressed');
            GM_setValue(storageKey('article', 'unsavedCompressed'), 'compressed');
            GM_setValue(storageKey('home', 'unsavedExpanded'), 'expanded');
            GM_setValue(storageKey('home', 'unsavedCompressed'), 'compressed');
            GM_setValue(storageKey('home', 'savedCompressed'), 'compressed');
            GM_setValue('deprecatedComponent', 'compressed');

        });

        it('does not remove configuration for saved components', () => {
            cleanStoredValues('article', mockConf);
            expect(GM_getValue(storageKey('article', 'savedExpanded'), null)).toBe('expanded');
            expect(GM_getValue(storageKey('article', 'savedCompressed'), null)).toBe('compressed');
            expect(GM_getValue(storageKey('home', 'savedCompressed'), null)).toBe('compressed');
        });

        it('removes configuration for no-longer-saved components', () => {
            cleanStoredValues('home', mockConf);
            expect(GM_getValue(storageKey('home', 'unsavedExpanded'), null)).toBeNull();
            expect(GM_getValue(storageKey('home', 'unsavedCompressed'), null)).toBeNull();
            expect(GM_getValue(storageKey('article', 'unsavedCompressed'), null)).toBe('compressed');
        });

        it('removes configuration for deprecated components', () => {
            cleanStoredValues('home', mockConf);
            expect(GM_getValue('deprecatedComponent', null)).toBeNull();
        });

    });

    describe('getPageType', () => {

        it('recognises the home page', () => {

            expect(getPageType('https://www.abc.net.au/')).toBe('home');

        });

        it('recognises an article page', () => {

            expect(getPageType('https://www.abc.net.au/news/2026-05-27/article-title/number')).toBe('article');

        });

        it('recognises unit testing', () => {

            expect(getPageType('file:///home/alittler/src/alr.userscripts/spec.html')).toBe('test');

        });

        it('returns null for unrecognised pages', () => {

            expect(getPageType('https://www.abc.net.au/news/politics')).toBeNull();
            expect(getPageType('https://www.alittleresearch.com.au')).toBeNull();

        });

    });

    describe('logUnexpectedEvent', () => {

        let consoleSpy;

        beforeEach(() => {
            // spy on console.warn()
            consoleSpy = new spyOn(console, 'warn');
        });

        it('valid source identifiers invoke console.warn()', () => {
            logUnexpectedEvent("conf", "Conf error.");
            expect(consoleSpy).toHaveBeenCalledWith("Configuration error: Conf error.");
            logUnexpectedEvent("dom", "DOM error.");
            expect(consoleSpy).toHaveBeenCalledWith("Possible DOM change: DOM error.");
        });

        it('invalid source identifiers report an error', () => {
            logUnexpectedEvent("invalid", "Invalid source.");
            expect(consoleSpy).toHaveBeenCalledWith("logUnexpectedEvent called with invalid source: Invalid source.");
        });

    });

    describe('mapExpandableComponent', () => {

        let expandableComponents;
        beforeEach(() => {

            // get references to the known expandable components
            expandableComponents = [];

            // in-body rail component
            expandableComponents.push({
                container: document.getElementById('railContainer'),
                root: workingSpace.querySelector('#railContainer > .Rail_root__abc123'),
                header: workingSpace.querySelector('#railContainer .Rail_header__abc123'),
                content: workingSpace.querySelector('#railContainer .Rail_content__abc123')
            });

            // sidebar rail component
            expandableComponents.push({
                container: document.getElementById('railSidebar'),
                root: workingSpace.querySelector('#railSidebar > .Rail_root__abc123'),
                header: workingSpace.querySelector('#railSidebar .Rail_header__abc123'),
                content: workingSpace.querySelector('#railSidebar .Grid_row__abc123')
             });

             // article summary
             expandableComponents.push({
                container: document.getElementById('articleSummary'),
                root: workingSpace.querySelector('#articleSummary .ArticleSummary_summary__abc123'),
                header: workingSpace.querySelector('#articleSummary h2'),
                content: workingSpace.querySelectorAll('#articleSummary p')
            });

            // contact form
            expandableComponents.push({
                container: document.getElementById('zendeskForm'),
                root: workingSpace.querySelector('#zendeskForm .ZendeskForm_zendeskForm__abc123'),
                header: workingSpace.querySelector('#zendeskForm h3'),
                content: workingSpace.querySelector('#zendeskForm form')
            });

            // top stories
            expandableComponents.push({
                container: document.getElementById('topStoriesFooter'),
                root: workingSpace.querySelector('#topStoriesFooter .TopStories_container__abc123'),
                header: workingSpace.querySelector('#topStoriesFooter header'),
                content: workingSpace.querySelector('#topStoriesFooter ol')
            });

            // aside with h2 heading
            expandableComponents.push({
                container: document.getElementById('asideWithH2'),
                root: workingSpace.querySelector('#asideWithH2'),
                header: workingSpace.querySelector('#asideWithH2 h2'),
                content: [ workingSpace.querySelector('#asideWithH2 ul') ]
            });

            // aside with rail header
            expandableComponents.push({
                container: document.getElementById('asideWithRailHeader'),
                root: workingSpace.querySelector('#asideWithRailHeader'),
                header: workingSpace.querySelector('#asideWithRailHeader .Rail_header__abc123'),
                content: [
                    workingSpace.querySelector('#asideWithRailHeader > div:nth-child(2)'),
                    workingSpace.querySelector('#asideWithRailHeader > div:nth-child(3)')
                ]
            });

            // in-article panel
            expandableComponents.push({
                container: document.getElementById('inArticlePanel'),
                root: workingSpace.querySelector('#inArticlePanel'),
                header: workingSpace.querySelector('#inArticlePanel h2'),
                content: [
                    workingSpace.querySelector('#inArticlePanel .Rail_header__abc123 > div:nth-child(2)'),
                    workingSpace.querySelector('#inArticlePanel .Panel_content__abc123 > div:nth-child(2)')
                ]
            });

        });

        it('finds roots passed directly', () => {
            for (const c of expandableComponents) {
                const parts = mapExpandableComponent(c.root);
                expect(parts.root).toBe(c.root);
            }
        });

        it('searches downwards for the component root', () => {
            for (const c of expandableComponents) {
                const parts = mapExpandableComponent(c.container);
                expect(parts.root).toBe(c.root);
            }
        });

        it('searches upwards for the component root', () => {
            for (const c of expandableComponents) {
                const parts = mapExpandableComponent(c.root.firstElementChild);
                expect(parts.root).toBe(c.root);
            }
        });

        it('returns null when no rail component root exists in the tree', () => {
            const testElement = document.getElementById('testElement');
            expect(mapExpandableComponent(testElement)).toBeNull();
        });

        it('correctly maps the root, header, and content', () => {
            for (const c of expandableComponents) {
                const parts = mapExpandableComponent(c.container);
                expect(parts.root).toBe(c.root);
                expect(parts.header).toBe(c.header);
                expect(parts.content).toEqual(c.content);
            }
        });
    });

    describe('onClickExpandable', () => {

        // verify that the parts of an expandable component respond property
        function expectExpandable(parts) {

            // compress expanded component
            onClickExpandable(parts.header, parts.content, null);
            for (let i = 0; i < parts.content.length; i++) {
                expect(parts.content[i].style.display).toBe('none');
            }
            expect(parts.header.style.cursor).toBe('zoom-in');

            // expand compressed component
            onClickExpandable(parts.header, parts.content, null);
            for (let i = 0; i < parts.content.length; i++) {
                expect(parts.content[i].style.display).toBe('block');
            }
            expect(parts.header.style.cursor).toBe('zoom-out');
        }

        let parts;
        beforeEach(() => {

            // get references to some test elements
            parts = {
                root: workingSpace.querySelector('#railContainer > .Rail_root__abc123'),
                header: workingSpace.querySelector('#railContainer .Rail_header__abc123'),
                content: workingSpace.querySelector('#railContainer .Rail_content__abc123')
            };

        });

        it('clicking on the default header hides content and makes the cursor zoom-in, without saving', () => {
            onClickExpandable(parts.header, parts.content, null);
            expect(parts.content.style.display).toBe('none');
            expect(parts.header.style.cursor).toBe('zoom-in');
            expect(GM_getValue('testExpandable', null)).toBeNull();
        });

        it('clicking on a compressed header makes content visible and cursor zoom-out', () => {
            onClickExpandable(parts.header, parts.content, null); // compresses the element
            onClickExpandable(parts.header, parts.content, null); // expands it again
            expect(parts.content.style.display).toBe('block');
            expect(parts.header.style.cursor).toBe('zoom-out');
            expect(GM_getValue('testExpandable', null)).toBeNull();
        });

        it('clicking on an expanded header hides the content, with saving', () => {
            onClickExpandable(parts.header, parts.content, 'testExpandable');
            expect(parts.content.style.display).toBe('none');
            expect(parts.header.style.cursor).toBe('zoom-in');
            expect(GM_getValue('testExpandable', null)).toBe('compressed');
        });

        it('clicking on a compressed header makes the content visible, with saving', () => {
            onClickExpandable(parts.header, parts.content, 'testExpandable'); // compresses the element
            onClickExpandable(parts.header, parts.content, 'testExpandable'); // expands it again
            expect(parts.content.style.display).toBe('block');
            expect(parts.header.style.cursor).toBe('zoom-out');
            expect(GM_getValue('testExpandable', null)).toBe('expanded');
        });

        it('handles NodeList contents', () => {
            // use the article summary, which has multiple paragraphs
            const parts = {
               root: workingSpace.querySelector('#articleSummary .ArticleSummary_summary__abc123'),
               header: workingSpace.querySelector('#articleSummary h2'),
               content: workingSpace.querySelectorAll('#articleSummary p')
           };
           expectExpandable(parts);
        });

        it('handles array contents', () => {
            // use the aside with rail header, which has mutliple div's
            const parts = {
                root: workingSpace.querySelector('#asideWithRailHeader'),
                header: workingSpace.querySelector('#asideWithRailHeader .Rail_header__abc123'),
                content: [
                    workingSpace.querySelector('#asideWithRailHeader > div:nth-child(2)'),
                    workingSpace.querySelector('#asideWithRailHeader > div:nth-child(3)')
                ]
            };
            expectExpandable(parts);
        });

    });


    describe('renderExpandable', () => {

        let parts;
        let makeExpandableSpy;
        let errorSpy;
        beforeEach(() => {

            // mock mapExpandableComponent
            parts = {
                root: workingSpace.querySelector('#railContainer > .Rail_root__abc123'),
                header: workingSpace.querySelector('#railContainer .Rail_header__abc123'),
                content: workingSpace.querySelector('#railContainer .Rail_content__abc123')
            };
            makeExpandableSpy = spyOn(this, 'mapExpandableComponent').and.returnValue(parts);


            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');
        });

        it('content is visible when startCompressed is not supplied', () => {
            renderExpandable(parts.root);
            expect(parts.content.style.display).not.toBe('none');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('content is visible and cursor is zoom-out when startCompressed is false', () => {
            renderExpandable(parts.root, false);
            expect(parts.content.style.display).not.toBe('none');
            expect(parts.header.style.cursor).toBe('zoom-out');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it ('content is compressed and cursor is zoom-in when startCompressed is true', () => {
            renderExpandable(parts.root, true);
            expect(parts.content.style.display).toBe('none');
            expect(parts.header.style.cursor).toBe('zoom-in');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('handles multiple content items', () => {
            // use the article summary, which has multiple lines
            let summary = {
               root: workingSpace.querySelector('#articleSummary .ArticleSummary_summary__abc123'),
               header: workingSpace.querySelector('#articleSummary h2'),
               content: workingSpace.querySelectorAll('#articleSummary p')
            }
            makeExpandableSpy.and.returnValue(summary);

            // start expanded
            renderExpandable(summary.root, false);
            expect(summary.header.style.cursor).toBe('zoom-out');
            for (let i = 0; i < summary.content.length; i++) {
                expect(summary.content[i].style.display).toBe('');
            }

            // start compressed
            renderExpandable(summary.root, true);
            expect(summary.header.style.cursor).toBe('zoom-in');
            for (let i = 0; i < summary.content.length; i++) {
                expect(summary.content[i].style.display).toBe('none');
            }

        });

        it('clicking invokes onClickExpandable with correct arguments', () => {
            const clickSpy = spyOn(this, 'onClickExpandable');
            renderExpandable(parts.root, true);
            parts.header.click();
            expect(clickSpy).toHaveBeenCalledTimes(1);
            expect(clickSpy).toHaveBeenCalledWith(parts.header, parts.content, null);
            renderExpandable(parts.root, true, 'testExpandable');
            parts.header.click();
            expect(clickSpy).toHaveBeenCalledTimes(2);
            expect(clickSpy).toHaveBeenCalledWith(parts.header, parts.content, 'testExpandable');
        });

        it('mouseover sets header background; mouseout resets it', () => {
            renderExpandable(parts.root, false);
            const originalBackgroundColor = parts.header.style.backgroundColor;
            parts.header.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
            expect(parts.header.style.backgroundColor).toBe('var(--nw-colour-theme-surface-tint)');
            parts.header.dispatchEvent(new MouseEvent('mouseout', { bubbles: true }));
            expect(parts.header.style.backgroundColor).toBe(originalBackgroundColor);
        });

        it('logs an unexpected event for a non-expandable component', () => {
            makeExpandableSpy.and.returnValue(null);
            renderExpandable(parts.root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

        it('logs an unexpected event for an expandable component with no content', () => {
            makeExpandableSpy.and.returnValue({
                root: parts.root,
                header: parts.header
            });
            renderExpandable(parts.root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

        it('log an unexpected event for an expandable component with no header', () => {
            makeExpandableSpy.and.returnValue({
                root: parts.root,
                content: parts.content
            });
            renderExpandable(parts.root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

    });


    describe('renderHidden', () => {

        it('hide single element', () => {
            const testElement = document.getElementById('testElement');
            testElement.style.display = 'block';
            renderHidden(testElement);
            expect(testElement.style.display).toBe('none');
        });

        it('hide rail element', () => {
            const railContainer = document.getElementById('railContainer');
            const railRoot = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
            const railChild = railRoot.firstElementChild;
            renderHidden(railRoot);
            expect(railRoot.style.display).toBe('none');
            expect(railContainer.style.display).not.toBe('none');
            expect(railChild.style.display).not.toBe('none');
        });

    });

    describe('storageKey', () => {

        it('constructs and deconstructs storage keys', () => {

            const sk = storageKey('cat', 'dog');
            expect(storageKeyCategory(sk)).toBe('cat');
            expect(storageKeyBare(sk)).toBe('dog');

        });

        it('handles keys containing the separator', () => {

            const sk = storageKey('cat', 'dog*');
            expect(storageKeyCategory(sk)).toBe('cat');
            expect(storageKeyBare(sk)).toBe('dog*');

        });

        it('handles keys containing CSS selectors', () => {

            const sk1 = storageKey('cat', '.dog');
            expect(storageKeyCategory(sk1)).toBe('cat');
            expect(storageKeyBare(sk1)).toBe('.dog');

            const sk2 = storageKey('cat', '#dog');
            expect(storageKeyCategory(sk2)).toBe('cat');
            expect(storageKeyBare(sk2)).toBe('#dog');

        });

        it('deconstucts deprecated keys', () => {

            const sk = '.deprecated_key';
            expect(storageKeyCategory(sk)).toBeNull();
            expect(storageKeyBare(sk)).toBe(sk);

        });

    });

});


// Mock up a rail element. See streamline.renderExpandable() for the structure
// of a rail element.
//
// Input:
//   id (string) - an id for the containing div
//   nonce (string) - an arbitrary string to append to class names
//   title (string) - the text content of the header
//   sidebar (boolean) - true to use sidebar style; false to use in-text style
//
// Returns: a div containing a rail element in the format used by the ABC site
function mockRailElement(id, nonce, title, sidebar = false) {

    // containing div
    const container = document.createElement('div');
    container.id = id;

    // rail root
    const root = document.createElement('div');
    root.className = 'Rail_root__' + nonce + ' Rail_sideScrolling__' + nonce;
    container.appendChild(root);

    // rail header
    const header = document.createElement('div');
    header.className = 'Rail_header__' + nonce;
    root.appendChild(header);
    if (title != null) {
        const headerContent = document.createElement('h2');
        headerContent.textContent = title;
        header.append(headerContent);
    }

    if (!sidebar) {
        // scrolling window
        const navigation = document.createElement('div');
        navigation.className = 'Rail_scrollNavigation__' + nonce;
        root.appendChild(navigation);
    }

    // content
    const content = document.createElement('div');
    content.className = (sidebar) ?
        'Grid_row__' + nonce :
        'Rail_content__' + nonce;
    root.appendChild(content);

    return container;

}
