///////////////////////////////////////////////////////////////////////////////
// Unit tests for ABC News scripts, partially generated by Github Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// streamline.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('streamline.js', () => {

    let workingSpace;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {
        // clear persistent values
        GM_clearValues();

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);

        // element identified by id
        const elementById = document.createElement('div');
        elementById.id = 'testElement';
        workingSpace.appendChild(elementById);

        // elements identified by class
        const elementsByClass = [
            document.createElement('div'),
            document.createElement('div')
        ];
        for (let e of elementsByClass) {
            e.className = 'testClass';
            workingSpace.appendChild(e);
        }

        // element identified by H2 heading test
        const headingContainer = mockRailElement('testHeadingContainer', 'abc123', 'Test Heading', false);
        workingSpace.appendChild(headingContainer);

        // mock in-body rail element
        const railContainer = mockRailElement('railContainer', 'abc123', 'In-body rail', false);
        workingSpace.appendChild(railContainer);

        // mock sidebar rail element
        const railSidebar = mockRailElement('railSidebar', 'abc123', 'Sidebar Rail', true);
        workingSpace.appendChild(railSidebar);

    });


    afterEach(() => {
        // remove the working space
        document.body.removeChild(workingSpace);
    });


    describe('applyConfiguration', () => {

        let elementById;
        let elementByClass;
        let elementByHeading;
        let errorSpy;
        let applyRendererSpy;
        let renderExpandableSpy;
        let renderHiddenSpy;

        beforeEach(() => {

            // get references to the test elements
            elementById = workingSpace.querySelector('#testElement');
            elementByClass = workingSpace.querySelector('.testClass');
            elementByHeading = workingSpace.querySelector('#testHeadingContainer .Rail_root__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');

            // spy on rendering functions
            applyRendererSpy = spyOn(this, 'applyRenderer').and.callThrough();
            renderExpandableSpy = spyOn(this, 'renderExpandable');
            renderHiddenSpy = spyOn(this, 'renderHidden');
        });

        it('applies configuration without saving', () => {
            const mockConfNoSave = {
                '#testElement': 'default',
                '.testClass': 'expanded',
                'Test Heading': 'compressed'
            };
            applyConfiguration("test", mockConfNoSave);
            expect(applyRendererSpy).toHaveBeenCalledTimes(2);
            expect(applyRendererSpy).not.toHaveBeenCalledWith('#testElement', jasmine.any(Function));
            expect(applyRendererSpy).toHaveBeenCalledWith('.testClass', jasmine.any(Function));
            expect(applyRendererSpy).toHaveBeenCalledWith('Test Heading', jasmine.any(Function));
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByClass, false, null);
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByHeading, true, null);
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('applies configuration with saving', () => {
            GM_setValue(storageKey('test', '.testClass'), 'compressed');
            const mockConfWithSave = {
                '#testElement': 'hidden',
                '.testClass': 'saved',
                'Test Heading': 'saved'
            };
            applyConfiguration("test", mockConfWithSave);
            expect(applyRendererSpy).toHaveBeenCalledTimes(3);
            expect(renderHiddenSpy).toHaveBeenCalledWith(elementById);
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByClass, true, storageKey('test', '.testClass'));
            expect(renderExpandableSpy).toHaveBeenCalledWith(elementByHeading, false, storageKey('test', 'Test Heading'));
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event for an invalid configuration value', () => {
            const mockConfBadValue = { '#testElement': 'badValue' };
            applyConfiguration("test", mockConfBadValue);
            expect(applyRendererSpy).not.toHaveBeenCalled();
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

    });

    describe('applyRenderer', () => {

        // mock rendering function
        function mockRender(target) {
            if (target != null) {
                target.setAttribute('data-rendered', 'true');
            }
        };

        let elementById;
        let elementsByClass;
        let elementByHeading;
        let errorSpy;

        beforeEach(() => {
            // get references to the test elements
            elementById = document.getElementById('testElement');
            elementsByClass = document.getElementsByClassName('testClass');
            elementByHeading = workingSpace.querySelector('#testHeadingContainer .Rail_root__abc123');

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');
        });

        it('logs unexpected events for invalid configuration keys', () => {
            applyRenderer('', mockRender);
            applyRenderer('#', mockRender);
            applyRenderer('.', mockRender);
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).toHaveBeenCalledTimes(3);
        });

        it('renders elements identified by id', () => {
            applyRenderer('#testElement', mockRender);
            expect(elementById.getAttribute('data-rendered')).toBe('true');
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            elementById.removeAttribute('data-rendered');
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('renders elements identified by class', () => {
            applyRenderer('.testClass', mockRender);
            for (let e of elementsByClass) {
                expect(e.getAttribute('data-rendered')).toBe('true');
                e.removeAttribute('data-rendered');
            }
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementByHeading.hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('renders elements identified by H2 heading text', () => {
            applyRenderer('Test Heading', mockRender);
            expect(elementByHeading.getAttribute('data-rendered')).toBe('true');
            expect(elementById.hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[0].hasAttribute('data-rendered')).toBeFalse();
            expect(elementsByClass[1].hasAttribute('data-rendered')).toBeFalse();
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event for an unmatched configuration key', () => {
            applyRenderer('Garbage', mockRender);
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

        it('logs an unexpected event for a missing rail root', () => {
            findRailRoot(elementByHeading).remove();
            applyRenderer('Test Heading', mockRender);
            expect(errorSpy).toHaveBeenCalledWith("conf", jasmine.any(String));
        });

    });

    describe('cleanStoredValues', () => {

        // mock configuration
        const mockConf = {
            'savedExpanded': 'saved',
            'savedCompressed': 'saved',
            'unsavedExpanded': 'expanded',
            'unsavedCompressed': 'compressed'
        };

        beforeEach(() => {

            // mock some stored values
            GM_setValue(storageKey('article', 'savedExpanded'), 'expanded');
            GM_setValue(storageKey('article', 'savedCompressed'), 'compressed');
            GM_setValue(storageKey('article', 'unsavedCompressed'), 'compressed');
            GM_setValue(storageKey('home', 'unsavedExpanded'), 'expanded');
            GM_setValue(storageKey('home', 'unsavedCompressed'), 'compressed');
            GM_setValue(storageKey('home', 'savedCompressed'), 'compressed');
            GM_setValue('deprecatedComponent', 'compressed');

        });

        it('does not remove configuration for saved components', () => {
            cleanStoredValues('article', mockConf);
            expect(GM_getValue(storageKey('article', 'savedExpanded'), null)).toBe('expanded');
            expect(GM_getValue(storageKey('article', 'savedCompressed'), null)).toBe('compressed');
            expect(GM_getValue(storageKey('home', 'savedCompressed'), null)).toBe('compressed');
        });

        it('removes configuration for no-longer-saved components', () => {
            cleanStoredValues('home', mockConf);
            expect(GM_getValue(storageKey('home', 'unsavedExpanded'), null)).toBeNull();
            expect(GM_getValue(storageKey('home', 'unsavedCompressed'), null)).toBeNull();
            expect(GM_getValue(storageKey('article', 'unsavedCompressed'), null)).toBe('compressed');
        });

        it('removes configuration for deprecated components', () => {
            cleanStoredValues('home', mockConf);
            expect(GM_getValue('deprecatedComponent', null)).toBeNull();
        });

    });

    describe('findRailRoot', () => {

        let railRoot;

        beforeEach(() => {
            // get a reference to the expected rail root
            railRoot = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
        });

        it('finds roots passed directly', () => {
            const trivialRailRoot = findRailRoot(railRoot);
            expect(trivialRailRoot).toBe(railRoot);
        });

        it('searches downwards for the rail root', () => {
            const railContainer = document.getElementById('railContainer');
            const downwardsRailRoot = findRailRoot(railContainer);
            expect(downwardsRailRoot).toBe(railRoot);
        });

        it('searches upwards for the rail root', () => {
            const railChild = railRoot.firstElementChild;
            const upwardsRailRoot = findRailRoot(railChild);
            expect(upwardsRailRoot).toBe(railRoot);
        });

        it('returns null when no rail root exists in the tree', () => {
            const testElement = document.getElementById('testElement');
            const nullRailRoot = findRailRoot(testElement);
            expect(nullRailRoot).toBeNull();
        });

    });

    describe('getPageType', () => {

        it('recognises the home page', () => {

            expect(getPageType('https://www.abc.net.au/')).toBe('home');

        });

        it('recognises an article page', () => {

            expect(getPageType('https://www.abc.net.au/news/2026-05-27/article-title/number')).toBe('article');

        });

        it('recognises unit testing', () => {

            expect(getPageType('file:///home/alittler/src/alr.userscripts/spec.html')).toBe('test');

        });

        it('returns null for unrecognised pages', () => {

            expect(getPageType('https://www.abc.net.au/news/politics')).toBeNull();
            expect(getPageType('https://www.alittleresearch.com.au')).toBeNull();

        });

    });

    describe('logUnexpectedEvent', () => {

        let consoleSpy;

        beforeEach(() => {
            // spy on console.warn()
            consoleSpy = new spyOn(console, 'warn');
        });

        it('valid source identifiers invoke console.warn()', () => {
            logUnexpectedEvent("conf", "Conf error.");
            expect(consoleSpy).toHaveBeenCalledWith("Configuration error: Conf error.");
            logUnexpectedEvent("dom", "DOM error.");
            expect(consoleSpy).toHaveBeenCalledWith("Possible DOM change: DOM error.");
        });

        it('invalid source identifiers report an error', () => {
            logUnexpectedEvent("invalid", "Invalid source.");
            expect(consoleSpy).toHaveBeenCalledWith("logUnexpectedEvent called with invalid source: Invalid source.");
        });

    });

    describe('onClickExpandable', () => {

        let root;
        let header;
        let content;

        beforeEach(() => {

            // get references to the test elements
            root = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
            header = workingSpace.querySelector('#railContainer .Rail_header__abc123')
            content = workingSpace.querySelector('#railContainer .Rail_content__abc123');

        });

        it('clicking on the default header hides content and makes the cursor zoom-in, without saving', () => {
            onClickExpandable(header, content, null);
            expect(content.style.display).toBe('none');
            expect(header.style.cursor).toBe('zoom-in');
            expect(GM_getValue('testExpandable', null)).toBeNull();
        });

        it('clicking on a compressed header makes content visible and cursor zoom-out', () => {
            onClickExpandable(header, content, null); // compresses the element
            onClickExpandable(header, content, null); // expands it again
            expect(content.style.display).toBe('block');
            expect(header.style.cursor).toBe('zoom-out');
            expect(GM_getValue('testExpandable', null)).toBeNull();
        });

        it('clicking on an expanded header hides the content, with saving', () => {
            onClickExpandable(header, content, 'testExpandable');
            expect(content.style.display).toBe('none');
            expect(header.style.cursor).toBe('zoom-in');
            expect(GM_getValue('testExpandable', null)).toBe('compressed');
        });

        it('clicking on a compressed header makes the content visible, with saving', () => {
            onClickExpandable(header, content, 'testExpandable'); // compresses the element
            onClickExpandable(header, content, 'testExpandable'); // expands it again
            expect(content.style.display).toBe('block');
            expect(header.style.cursor).toBe('zoom-out');
            expect(GM_getValue('testExpandable', null)).toBe('expanded');
        });

    });


    describe('renderExpandable', () => {

        let expandableElements;
        let errorSpy;
        beforeEach(() => {

            // build a list of expandable elements of different types
            expandableElements = [];

            // in-body rail element
            expandableElements.push({
                root: workingSpace.querySelector('#railContainer > .Rail_root__abc123'),
                header: workingSpace.querySelector('#railContainer .Rail_header__abc123'),
                content: workingSpace.querySelector('#railContainer .Rail_content__abc123')
            });

            // sidebar rail element
            expandableElements.push({
                root: workingSpace.querySelector('#railSidebar > .Rail_root__abc123'),
                header: workingSpace.querySelector('#railSidebar .Rail_header__abc123'),
                content: workingSpace.querySelector('#railSidebar .Grid_row__abc123')
            });

            // spy on the error handler
            errorSpy = spyOn(this, 'logUnexpectedEvent');
        });

        it('content is visible when startCompressed is not supplied', () => {
            for (const e of expandableElements) {
                renderExpandable(e.root);
                expect(e.content.style.display).not.toBe('none');
            }
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('content is visible and cursor is zoom-out when startCompressed is false', () => {
            for (const e of expandableElements) {
                renderExpandable(e.root, false);
                expect(e.content.style.display).not.toBe('none');
                expect(e.header.style.cursor).toBe('zoom-out');
            }
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it ('content is compressed and cursor is zoom-in when startCompressed is true', () => {
            for (const e of expandableElements) {
                renderExpandable(e.root, true);
                expect(e.content.style.display).toBe('none');
                expect(e.header.style.cursor).toBe('zoom-in');
            }
            expect(errorSpy).not.toHaveBeenCalled();
        });

        it('clicking invokes onClickExpandable with correct arguments', () => {
            const e = expandableElements[0];
            const clickSpy = spyOn(this, 'onClickExpandable');
            renderExpandable(e.root, true);
            e.header.click();
            expect(clickSpy).toHaveBeenCalledTimes(1);
            expect(clickSpy).toHaveBeenCalledWith(e.header, e.content, null);
            renderExpandable(e.root, true, 'testExpandable');
            e.header.click();
            expect(clickSpy).toHaveBeenCalledTimes(2);
            expect(clickSpy).toHaveBeenCalledWith(e.header, e.content, 'testExpandable');
        });

        it('mouseover sets header background; mouseout resets it', () => {
            const e = expandableElements[0];
            renderExpandable(e.root, false);
            const originalBackgroundColor = e.header.style.backgroundColor;
            e.header.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
            expect(e.header.style.backgroundColor).toBe('var(--nw-colour-theme-surface-tint)');
            e.header.dispatchEvent(new MouseEvent('mouseout', { bubbles: true }));
            expect(e.header.style.backgroundColor).toBe(originalBackgroundColor);
        });

        it('logs an unexpected event for an element with no rail root', () => {
            const testElement = document.getElementById('testElement');
            renderExpandable(testElement, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

        it('logs an unexpected event for a rail element with no content', () => {
            const e = expandableElements[0];
            e.content.remove();
            renderExpandable(e.root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

        it('log an unexpected event for a rail element with no header', () => {
            const e = expandableElements[0];
            e.header.remove();
            renderExpandable(e.root, false);
            expect(errorSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

    });


    describe('renderHidden', () => {

        it('hide single element', () => {
            const testElement = document.getElementById('testElement');
            testElement.style.display = 'block';
            renderHidden(testElement);
            expect(testElement.style.display).toBe('none');
        });

        it('hide rail element', () => {
            const railContainer = document.getElementById('railContainer');
            const railRoot = workingSpace.querySelector('#railContainer > .Rail_root__abc123');
            const railChild = railRoot.firstElementChild;
            renderHidden(railRoot);
            expect(railRoot.style.display).toBe('none');
            expect(railContainer.style.display).not.toBe('none');
            expect(railChild.style.display).not.toBe('none');
        });

    });

    describe('storageKey', () => {

        it('constructs and deconstructs storage keys', () => {

            const sk = storageKey('cat', 'dog');
            expect(storageKeyCategory(sk)).toBe('cat');
            expect(storageKeyBare(sk)).toBe('dog');

        });

        it('handles keys containing the separator', () => {

            const sk = storageKey('cat', 'dog*');
            expect(storageKeyCategory(sk)).toBe('cat');
            expect(storageKeyBare(sk)).toBe('dog*');

        });

        it('handles keys containing CSS selectors', () => {

            const sk1 = storageKey('cat', '.dog');
            expect(storageKeyCategory(sk1)).toBe('cat');
            expect(storageKeyBare(sk1)).toBe('.dog');

            const sk2 = storageKey('cat', '#dog');
            expect(storageKeyCategory(sk2)).toBe('cat');
            expect(storageKeyBare(sk2)).toBe('#dog');

        });

        it('deconstucts deprecated keys', () => {

            const sk = '.deprecated_key';
            expect(storageKeyCategory(sk)).toBeNull();
            expect(storageKeyBare(sk)).toBe(sk);

        });

    });

});


// Mock up a rail element. See streamline.renderExpandable() for the structure
// of a rail element.
//
// Input:
//   id (string) - an id for the containing div
//   nonce (string) - an arbitrary string to append to class names
//   title (string) - the text content of the header
//   sidebar (boolean) - true to use sidebar style; false to use in-text style
//
// Returns: a div containing a rail element in the format used by the ABC site
function mockRailElement(id, nonce, title, sidebar = false) {

    // containing div
    const container = document.createElement('div');
    container.id = id;

    // rail root
    const root = document.createElement('div');
    root.className = 'Rail_root__' + nonce + ' Rail_sideScrolling__' + nonce;
    container.appendChild(root);

    // rail header
    const header = document.createElement('div');
    header.className = 'Rail_header__' + nonce;
    root.appendChild(header);
    if (title != null) {
        const headerContent = document.createElement('h2');
        headerContent.textContent = title;
        header.append(headerContent);
    }

    if (!sidebar) {
        // scrolling window
        const navigation = document.createElement('div');
        navigation.className = 'Rail_scollNavigation__' + nonce;
        root.appendChild(navigation);
    }

    // content
    const content = document.createElement('div');
    content.className = (sidebar) ?
        'Grid_row__' + nonce :
        'Rail_content__' + nonce;
    root.appendChild(content);

    return container;

}
