///////////////////////////////////////////////////////////////////////////////
// Unit tests for Bureau of Meteorology scripts, partially generated by Github
// Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// streamline.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('streamline.js', () => {

    let workingSpace;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);

    });


    afterEach(() => {
        // remove the working space
        document.body.removeChild(workingSpace);
    });


    ///////////////////////////////////////////////////////////////////////////
    // applyComponentOrder
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyComponentOrder', () => {

        let e1;
        let e2;
        let e3;
        let map;
        let unexpectedEventSpy;
        beforeEach(() => {

            // create some components that we can move around
            e1 = document.createElement('div');
            e2 = document.createElement('div');
            e3 = document.createElement('div');
            workingSpace.appendChild(e1);
            workingSpace.appendChild(e2);
            workingSpace.appendChild(e3);

            // build a map
            map = { 'e1': e1, 'e2': e2, 'e3': e3 };

            // mock the unexpected event handler
            unexpectedEventSpy = spyOn(this, 'logUnexpectedEvent');

        });

        it('reorders all components', () => {

            const order = [ 'e3', 'e2', 'e1' ];
            applyComponentOrder(map, order);
            expect(workingSpace.children.length).toBe(3);
            expect(workingSpace.children.item(0)).toBe(e3);
            expect(workingSpace.children.item(1)).toBe(e2);
            expect(workingSpace.children.item(2)).toBe(e1);
            expect(unexpectedEventSpy).not.toHaveBeenCalled();

        });

        it('pushes unordered components to the end', () => {

            const order = [ 'e3', 'e1' ];
            applyComponentOrder(map, order);
            expect(workingSpace.children.length).toBe(3);
            expect(workingSpace.children.item(0)).toBe(e3);
            expect(workingSpace.children.item(1)).toBe(e1);
            expect(workingSpace.children.item(2)).toBe(e2);
            expect(unexpectedEventSpy).not.toHaveBeenCalled();

        });

        it('reorders a single component', () => {

            e2.remove();
            e3.remove();
            const order = [  'e1' ];
            applyComponentOrder(map, order);
            expect(workingSpace.children.length).toBe(1);
            expect(workingSpace.children.item(0)).toBe(e1);
            expect(unexpectedEventSpy).not.toHaveBeenCalled();

        });

        it('log an unexpected event for an unrecognised order element', () => {

            const order = [ 'e3', 'e2', 'junk', 'e1' ];
            applyComponentOrder(map, order);
            expect(workingSpace.children.length).toBe(3);
            expect(workingSpace.children.item(0)).toBe(e3);
            expect(workingSpace.children.item(1)).toBe(e2);
            expect(workingSpace.children.item(2)).toBe(e1);
            expect(unexpectedEventSpy).toHaveBeenCalledWith("conf", jasmine.any(String));

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleCompressed
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleCompressed', () => {

        let e1;
        let e2;
        let e3;
        let defaultSetSpy;
        let aboutStationSpy;
        beforeEach(() => {

            // create some components that we can compress
            e1 = document.createElement('div');
            e2 = document.createElement('div');
            e3 = document.createElement('div');
            workingSpace.appendChild(e1);
            workingSpace.appendChild(e2);
            workingSpace.appendChild(e3);

            // mock applyDisplayStyleCompressedDefaultSet that returns e1 and e2
            defaultSetSpy = spyOn(this, 'applyDisplayStyleCompressedDefaultSet').and.returnValue([ e1, e2 ]);

            // mock applyDisplayStyleCompressedAboutStation that does nothing
            aboutStationSpy = spyOn(this, 'applyDisplayStyleCompressedAboutStation');

        });

        it('compresses (only) the default set', () => {

            // mock getComponentKey that returns a key with the default behaviour
            spyOn(this, 'getComponentKey').and.returnValue('genericComponent');

            // compress the default set (e1 and e2)
            applyDisplayStyleCompressed(workingSpace, null, true);
            expect(e1.style.display).toBe('none');
            expect(e2.style.display).toBe('none');
            expect(e3.style.display).toBe('');

            // uncompress
            applyDisplayStyleCompressed(workingSpace, null, false);
            expect(e1.style.display).toBe('');
            expect(e2.style.display).toBe('');
            expect(e3.style.display).toBe('');

        });

        it('invokes special case for aboutStation', () => {

            // mock getComponentKey that returns 'aboutStation'
            const componentKeySpy = spyOn(this, 'getComponentKey').and.returnValue('aboutStation');

            // check that the aboutStation case is involed with the default set (e1 and e2)
            applyDisplayStyleCompressed(workingSpace, null, true);
            expect(aboutStationSpy).toHaveBeenCalledWith([e1, e2]);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyles
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyles', () => {

        let observerSpy;
        let unexpectedEventSpy;
        beforeEach(() => {

            // mock the display observer
            // TODO: verify that the observer is set up with the correct callback
            observerSpy = spyOn(this, 'applyDisplayStyleObserver');

            // mock the unexpected event handler
            unexpectedEventSpy = spyOn(this, 'logUnexpectedEvent');

        });

        it('sets up display style observers', () => {

            const map = {
                'defaultComponent': document.createElement('div'),
                'hiddenComponent': document.createElement('div'),
                'compressedComponent': document.createElement('div'),
                'expandedComponent': document.createElement('div')
            };
            const displayConf = {
                'defaultComponent': 'default',
                'hiddenComponent': 'hidden',
                'compressedComponent': 'compressed',
                'expandedComponent': 'expanded'
            };
            applyDisplayStyles(map, displayConf);
            expect(observerSpy).toHaveBeenCalledTimes(3);
            expect(observerSpy).toHaveBeenCalledWith(map['hiddenComponent'], jasmine.any(Function));
            expect(observerSpy).toHaveBeenCalledWith(map['compressedComponent'], jasmine.any(Function));
            expect(observerSpy).toHaveBeenCalledWith(map['expandedComponent'], jasmine.any(Function));
            expect(unexpectedEventSpy).not.toHaveBeenCalled();

        });

        it('logs an unexpected event for an invalid display style value', () => {

            const map = {
                'component': document.createElement('div')
            };
            const displayConf = {
                'component': 'junk'
            };
            applyDisplayStyles(map, displayConf);
            expect(observerSpy).not.toHaveBeenCalled();
            expect(unexpectedEventSpy).toHaveBeenCalledWith("conf", jasmine.any(String));

        });

        it('logs an unexpeced event for an invalid configuration key', () => {

            const map = {
                'component': document.createElement('div')
            };
            const displayConf = {
                'notComponent': 'hidden'
            };
            applyDisplayStyles(map, displayConf);
            expect(observerSpy).not.toHaveBeenCalled();
            expect(unexpectedEventSpy).toHaveBeenCalledWith("conf", jasmine.any(String));

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleCompressedAboutStation
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleCompressedAboutStation', () => {

        let e1;
        let e2;
        let morePastWeather;
        let pastWeatherBody;
        let pastWeatherButtons;
        let unexpectedEventSpy;
        beforeEach(() => {

            // mock some elements that aren't part of the About Station component
            e1 = document.createElement('div');
            e2 = document.createElement('div');
            workingSpace.appendChild(e1);
            workingSpace.appendChild(e2);

            // mock the About Station component
            morePastWeather = document.createElement('div');
            morePastWeather.classList.add('past-bom-component-container-3-1-C25_CTA');
            pastWeatherBody = document.createElement('div');
            pastWeatherBody.classList.add('bom-body');
            morePastWeather.appendChild(pastWeatherBody);
            pastWeatherButtons = document.createElement('div');
            pastWeatherButtons.classList.add('cta-module__button-container');
            morePastWeather.appendChild(pastWeatherButtons);
            workingSpace.appendChild(morePastWeather);

            // spy on expected events
            unexpectedEventSpy = spyOn(window, 'logUnexpectedEvent');

        });

        it('removes the "more past weather container" and adds its body and buttons', () => {

            // mock elements to compress
            let elementsToCompress = [ e1, morePastWeather, e2 ];

            // verify that morePastWeather is replaced by the body and buttons (at the end of the list)
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ e1, e2, pastWeatherBody, pastWeatherButtons ]);
            expect(unexpectedEventSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event when the "more past weather" container is found but the body is missing', () => {

            // if the body is missing, morePastWeather is still removed from list, but the buttons are added
            pastWeatherBody.remove();
            let elementsToCompress = [ morePastWeather ];
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ pastWeatherButtons]);
            expect(unexpectedEventSpy).toHaveBeenCalledWith('dom', jasmine.any(String));

        });

        it('logs an unexpected event when the "more past weather" container is found but missing buttons', () => {

            // if the buttons are missing, morePastWeather is still removed from list, but the body is added
            pastWeatherButtons.remove();
            let elementsToCompress = [ morePastWeather ];
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ pastWeatherBody ]);
            expect(unexpectedEventSpy).toHaveBeenCalledWith('dom', jasmine.any(String));

        });

        it('logs an unexpected event when the "more past weather" container is missing', () => {

            let elementsToCompress = [ e1 ];
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ e1 ]);
            expect(unexpectedEventSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleCompressedAboutStation
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleCompressedDefaultSet', () => {

        let root;
        let titleArea;
        beforeEach(() => {

            // create a root element
            root = document.createElement('div');
            workingSpace.appendChild(root);

            // create a title area put don't insert it into the tree yet
            titleArea = document.createElement('div');
        });

        it('returns the root when no title area exists', () => {

            const set = applyDisplayStyleCompressedDefaultSet(root, null);
            expect(set).toEqual([ root ]);

        });

        it('returns nothing when the root is the title area', () => {

            const set = applyDisplayStyleCompressedDefaultSet(root, root);
            expect(set).toEqual([]);

        });

        it('returns nothing when there are no paths other than the title area', () => {

            // root element with single title area as child
            root.appendChild(titleArea);
            const set1 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set1).toEqual([]);

            // root element with single path to title area
            const e1 = document.createElement('div');
            root.appendChild(e1);
            e1.appendChild(titleArea);
            const set2 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set2).toEqual([]);

        });

        it('returns non-ancestors of the title area', () => {

            // other elements at the same level as the title area
            const e1 = document.createElement('div');
            const e2 = document.createElement('div');
            root.appendChild(e1);
            root.appendChild(titleArea);
            root.appendChild(e2);
            const set1 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set1).toEqual([ e1, e2 ]);

            // other elements at the same level as the title area's parent
            e1.appendChild(titleArea);
            const set2 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set2).toEqual([ e2 ]);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleExpandable
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleExpandable', () => {

        let root;
        let titleArea;
        beforeEach(() => {

            // mock a component with title area
            key = 'testKey';
            root = document.createElement('div');
            root.backgroundColor = 'white';
            workingSpace.appendChild(root);
            titleArea = document.createElement('div');
            root.appendChild(titleArea);

        });

        it('invokes applyDisplayStyleExpandableSync when the title area is resolved', (done) => {

            // mock getComponentTitleArea and applyDisplayStyleExpandableSync
            const getComponentTitleAreaSpy = spyOn(this, 'getComponentTitleArea').and.returnValue(Promise.resolve(titleArea));
            const applyDisplayStyleExpandableSyncSpy = spyOn(this, 'applyDisplayStyleExpandableSync');

            // test with startCompressed = true
            applyDisplayStyleExpandable(root, key, true);
            setTimeout(() => {
                expect(applyDisplayStyleExpandableSyncSpy).toHaveBeenCalledWith(root, titleArea, true);
            }, 0);

            // test with startCompressed = false
            applyDisplayStyleExpandableSyncSpy.calls.reset();
            applyDisplayStyleExpandable(root, key, false);
            setTimeout(() => {
                expect(applyDisplayStyleExpandableSyncSpy).toHaveBeenCalledWith(root, titleArea, false);
                done();
            }, 0);

        });

        it('invokes applyDisplayStyleCompressed with correct parameters', () => {

            const applyDisplayStyleCompressedSpy = spyOn(this, 'applyDisplayStyleCompressed');

            // with fresh component and startCompressed = true
            titleArea.style.cursor = '';
            applyDisplayStyleExpandableSync(root, titleArea, true);
            expect(applyDisplayStyleCompressedSpy).toHaveBeenCalledWith(root, titleArea, true);

            // with fresh component and startCompressed = false
            titleArea.style.cursor = '';
            applyDisplayStyleCompressedSpy.calls.reset();
            applyDisplayStyleExpandableSync(root, titleArea, false);
            expect(applyDisplayStyleCompressedSpy).toHaveBeenCalledWith(root, titleArea, false);

            // with previously-compressed component
            titleArea.style.cursor  = 'zoom-in';
            applyDisplayStyleCompressedSpy.calls.reset();
            applyDisplayStyleExpandableSync(root, titleArea, false);
            expect(applyDisplayStyleCompressedSpy).toHaveBeenCalledWith(root, titleArea, true);

            // with previously-expanded component
            titleArea.style.cursor  = 'zoom-out';
            applyDisplayStyleCompressedSpy.calls.reset();
            applyDisplayStyleExpandableSync(root, titleArea, true);
            expect(applyDisplayStyleCompressedSpy).toHaveBeenCalledWith(root, titleArea, false);

        });

        it('applies expandable styling when invoked synchronously', () => {

            // cursor is zoom-out when startCompressed is false
            titleArea.style.cursor = '';
            applyDisplayStyleExpandableSync(root, titleArea, false);
            expect(titleArea.style.cursor).toBe('zoom-out');

            // cursor is zoom-in when startCompressed is true
            titleArea.style.cursor = '';
            applyDisplayStyleExpandableSync(root, titleArea, true);
            expect(titleArea.style.cursor).toBe('zoom-in');

            // clicking invokes onClickExpandableComponebt with correct arguments
            const clickSpy = spyOn(this, 'onClickExpandableComponent');
            applyDisplayStyleExpandableSync(root, titleArea);
            titleArea.click();
            expect(clickSpy).toHaveBeenCalledWith(root, titleArea);

            // mouseover sets header background to sitConf.theme.expandableBackground; mouseout resets it
            const originalBackgroundColor = root.style.backgroundColor;
            titleArea.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
            expect(titleArea.style.backgroundColor).toBe(siteConf.theme.expandableBackground);
            titleArea.dispatchEvent(new MouseEvent('mouseout', { bubbles: true }));
            expect(titleArea.style.backgroundColor).toBe(originalBackgroundColor);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleHidden
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleHidden', () => {

        let root;
        beforeEach(() => {

            // mock component
            root = document.createElement('div');
            workingSpace.appendChild(root);

        });

        it('suppresses display of the component', () => {

            applyDisplayStyleHidden(root);
            expect(root.style.display).toBe('none');

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleObserver
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleObserver', () => {

        let root;
        beforeEach(() => {

            // mock component
            root = document.createElement('div');
            workingSpace.appendChild(root);

        });

        it('applies the display style immediately and again after any change', (done) => {

            // mock rendering function that just sets a flag
            let renderCalled = false;
            let mockRender = function () { renderCalled = true; };

            // apply the style and set up the observer
            applyDisplayStyleObserver(root, mockRender);
            expect(renderCalled).toBeTrue();

            // make a change and verify that the component is re-rendered at the next tick
            renderCalled = false;
            const e1 = document.createElement('div');
            root.appendChild(e1);
            setTimeout(() => {
                expect(renderCalled).toBeTrue();
                done();
            }, 0);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // buildComponentMapHome
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('buildComponentMapHome', () => {

        let mainPageContent;
        beforeEach(() => {

            // mock the main page content container
            mainPageContent = document.createElement('div');
            mainPageContent.id = 'block-mainpagecontent';
            workingSpace.appendChild(mainPageContent);

        });

        it('maps recognised home page components', async () => {

            // mock some content for the home page
            const homepageHeader = document.createElement('div');
            homepageHeader.classList.add('bom-homepage-header');
            mainPageContent.appendChild(homepageHeader);
            const capitalForecast = document.createElement('div');
            capitalForecast.classList.add('homepage-content-top-wrapper');
            mainPageContent.appendChild(capitalForecast);
            const weatherMapContainer = document.createElement('div');
            const weatherMapChild = document.createElement('div');
            weatherMapChild.setAttribute('data-component', 'bom-spatial-map');
            weatherMapContainer.appendChild(weatherMapChild);
            mainPageContent.appendChild(weatherMapContainer);

            // build and verify the map
            const map = await buildComponentMapHome();
            expect(Object.keys(map).sort()).toEqual(['capitalForecast', 'homepageHeader', 'weatherMap']);
            expect(map.homepageHeader).toBe(homepageHeader);
            expect(map.capitalForecast).toBe(capitalForecast);
            expect(map.weatherMap).toBe(weatherMapContainer);

        });

        it('resolves an empty map when no recognised components are present', async () => {

            // mock an unrecognised component
            const unknown = document.createElement('div');
            unknown.classList.add('some-random-class');
            mainPageContent.appendChild(unknown);

            // build and verify the map
            const map = await buildComponentMapHome();
            expect(map).toEqual({});

        });

        it('rejects when the home page content element is missing', async () => {

            mainPageContent.remove();
            const result = buildComponentMapHome();
            await expectAsync(result).toBeRejectedWithError(ReferenceError);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // buildComponentMapLocation
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('buildComponentMapLocation', () => {

        let mainPageContent;
        let locationPageModule;
        beforeEach(() => {

            // mock the the main page content container
            mainPageContent = document.createElement('div');
            mainPageContent.id = 'block-mainpagecontent';
            workingSpace.appendChild(mainPageContent);

            // mock the "page module" (tab container) but don't add it yet (this happens later)
            locationPageModule = document.createElement('div');
            locationPageModule.classList.add('location-page-module');

        });

        it('maps known tabs and components when location-page-module appears', async () => {

            // mock tabs
            const todayTab = document.createElement('div');
            todayTab.id = 'bom-tab-panel-today';
            const todaySection = document.createElement('section');
            todaySection.classList.add('tc-today-C04_WeatherGlanceMoreAboutToday-1');
            todayTab.appendChild(todaySection);
            locationPageModule.appendChild(todayTab);
            const sevenDaysTab = document.createElement('div');
            sevenDaysTab.id = 'bom-tab-panel-7-days';
            const sevenDaySection = document.createElement('section');
            sevenDaySection.classList.add('tc-7-days-C10_ForecastWithAccordion-0');
            sevenDaysTab.appendChild(sevenDaySection);
            locationPageModule.appendChild(sevenDaysTab);
            const pastTab = document.createElement('div');
            pastTab.id = 'bom-tab-panel-past';
            const pastSection = document.createElement('section');
            pastSection.classList.add('tc-past-C66_ObservationChart-2');
            pastTab.appendChild(pastSection);
            locationPageModule.appendChild(pastTab);

            // get a promise to build the map
            const mapPromise = buildComponentMapLocation();

            // mutate after starting observation to trigger resolve
            mainPageContent.appendChild(locationPageModule);

            // verify the map
            const map = await mapPromise;
            expect(Object.keys(map).sort()).toEqual(['past', 'sevenDays', 'today']);
            expect(map.today.moreAboutToday).toBe(todaySection);
            expect(map.sevenDays.sevenDayForecast).toBe(sevenDaySection);
            expect(map.past.observationChart).toBe(pastSection);

        });

        it('logs an unexpected event for an unrecognised tab', async () => {

            // add a nonsense tab
            const mockTab = document.createElement('div');
            mockTab.id = 'not-a-tab';
            const mockSection = document.createElement('section');
            mockSection.classList.add('not-a-section');
            mockTab.appendChild(mockSection);
            locationPageModule.appendChild(mockTab);

            // spy on the unexpected event handler
            const unexpectedEventSpy = spyOn(this, 'logUnexpectedEvent');

            // get a promise to build the map
            const mapPromise = buildComponentMapLocation();

            // mutate after starting observation to trigger resolve
            mainPageContent.appendChild(locationPageModule);

            // check that an unexpected event is logged
            await mapPromise;
            expect(unexpectedEventSpy).toHaveBeenCalledWith("dom", jasmine.any(String));

        });

        it('rejects when the location page content container is missing', async () => {

            mainPageContent.remove();
            const result = buildComponentMapLocation();
            await expectAsync(result).toBeRejectedWithError(ReferenceError);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // getComponentKey
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('getComponentKey', () => {

        it('returns null for an unrecognised component', () => {

            const e1 = document.createElement('div');
            workingSpace.appendChild(e1);
            expect(getComponentKey(e1)).toBeNull();

        });

        xit('use logUnexpectedEvent to detect issues in component recognition', () => {

            // We don't bother with a unit test for the regular case; problems
            // with component recognition should be logged by logUnexpectedEvent

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // getComponentTitleArea
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('getComponentTitleArea', () => {

        let root;
        beforeEach(() => {

            // mock component
            root = document.createElement('div');
            workingSpace.appendChild(root);

        });

        it('resolves immediately when the title area already exists', async () => {

            // mock up a title area
            const titleArea = document.createElement('div');
            titleArea.classList.add('data-be-aware-title');
            root.appendChild(titleArea);

            // verify that the promise resolve immediately
            const result = await getComponentTitleArea(root, 'dataStatement');
            expect(result).toBe(titleArea);

        });

        it('resolves when the title area appears after invocation', async () => {

            // mock up a title area but don't add it yet
            const titleArea = document.createElement('div');
            titleArea.classList.add('data-be-aware-title');

            // get a promise to resolve the title area
            const promise = getComponentTitleArea(root, 'dataStatement');

            // add the title area and check the promise
            root.appendChild(titleArea);
            const result = await promise;
            expect(result).toBe(titleArea);

        });

        it('returns null for an unrecognised component', () => {

            const unexpectedEventSpy = spyOn(this, 'logUnexpectedEvent');
            const titleArea = getComponentTitleAreaSync(root, 'badKey');
            expect(titleArea).toBeNull();
            expect(unexpectedEventSpy).toHaveBeenCalledWith("conf", jasmine.any(String));

        });

        xit('use logUnexpectedEvent to detect issues in title area recognition', () => {

            // We don't bother with a unit test for the regular case; problems
            // with title area recognition should be logged by logUnexpectedEvent

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // getPageKey
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('getPageKey', () => {

        it('returns "home" for the BoM homepage', () => {

            expect(getPageKey("https://www.bom.gov.au/")).toBe('home');

        });

        it('returns "location" for BoM location pages', () => {

            expect(getPageKey("https://www.bom.gov.au/location/australia/new-south-wales/illawarra/bnsw_pt014-wollongong")).toBe('location');
            expect(getPageKey("https://www.bom.gov.au/location/australia/new-south-wales/metropolitan/bnsw_pt111-parramatta")).toBe('location');

        });

        it('returns "test" when executing unit tests', () => {

            expect(getPageKey("file:///C:/Users/xxxx/Source/alr.userscripts/tests/bom.tests.html")).toBe('test');
            expect(getPageKey("file:///home/xxxx/src//alr.userscripts/tests/bom.tests.html")).toBe('test');

        });

        it('returns null for other pages', () => {

            expect(getPageKey("https://www.bom.gov.au/weather-and-climate/warnings-and-alerts")).toBeNull();
            expect(getPageKey("https://www.alittleresearch.com.au")).toBeNull();

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // getTabKey
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('getTabKey', () => {

        it('returns null for an unrecognised component', () => {

            const e1 = document.createElement('div');
            e1.className = "not-a-tab";
            workingSpace.appendChild(e1);
            expect(getTabKey(e1)).toBeNull();

        });

        xit('use logUnexpectedEvent to detect issues in tab recognition', () => {

            // We don't bother with a unit test for the regular case; problems
            // with tab recognition should be logged by logUnexpectedEvent

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // logUnexpectedEvent
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('logUnexpectedEvent', () => {

        let consoleSpy;
        beforeEach(() => {
            // spy on console.warn()
            consoleSpy = new spyOn(console, 'warn');
        });

        it('valid source identifiers invoke console.warn()', () => {

            logUnexpectedEvent("conf", "Conf error.");
            expect(consoleSpy).toHaveBeenCalledWith("Configuration error: Conf error.");

            logUnexpectedEvent("dom", "DOM error.");
            expect(consoleSpy).toHaveBeenCalledWith("Possible DOM change: DOM error.");

        });

        it('invalid source identifiers report an error', () => {

            logUnexpectedEvent("invalid", "Invalid source.");
            expect(consoleSpy).toHaveBeenCalledWith("logUnexpectedEvent called with invalid source: Invalid source.");

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // onClickExpandableComponent
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('onClickExpandableComponent', () => {

        let root;
        let titleArea;
        let contentArea;
        let applyDisplayStyleSpy;
        beforeEach(() => {

            // mock an expandable element
            root = document.createElement('div');
            workingSpace.appendChild(root);
            titleArea = document.createElement('div');
            root.appendChild(titleArea);
            contentArea = document.createElement('div');
            root.appendChild(contentArea);

            // spy on the the renderer
            applyDisplayStyleSpy = spyOn(this, 'applyDisplayStyleCompressed');

        });

        it('compresses an expanded component', () => {

            // mimic an expanded component by setting the title cursor style to zoom-out
            titleArea.style.cursor = "zoom-out";

            // simulate a click
            onClickExpandableComponent(root, titleArea);
            expect(titleArea.style.cursor).toBe("zoom-in");
            expect(applyDisplayStyleSpy).toHaveBeenCalledWith(root, titleArea, true);

        });

        it('expands a compressed component', () => {

            // mimic a compressed component by setting the title cursor style to zoom-in
            titleArea.style.cursor = "zoom-in";

            // simulate a click
            onClickExpandableComponent(root, titleArea);
            expect(titleArea.style.cursor).toBe("zoom-out");
            expect(applyDisplayStyleSpy).toHaveBeenCalledWith(root, titleArea, false);

        });

    });

});
