///////////////////////////////////////////////////////////////////////////////
// Unit tests for Bureau of Meteorology scripts, partially generated by Github
// Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// streamline.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('streamline.js', () => {

    let workingSpace;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);

    });


    afterEach(() => {
        // remove the working space
        document.body.removeChild(workingSpace);
    });


    ///////////////////////////////////////////////////////////////////////////
    // logUnexpectedEvent
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('logUnexpectedEvent', () => {

        let consoleSpy;

        beforeEach(() => {
            // spy on console.warn()
            consoleSpy = new spyOn(console, 'warn');
        });

        it('valid source identifiers invoke console.warn()', () => {
            logUnexpectedEvent("conf", "Conf error.");
            expect(consoleSpy).toHaveBeenCalledWith("Configuration error: Conf error.");
            logUnexpectedEvent("dom", "DOM error.");
            expect(consoleSpy).toHaveBeenCalledWith("Possible DOM change: DOM error.");
        });

        it('invalid source identifiers report an error', () => {
            logUnexpectedEvent("invalid", "Invalid source.");
            expect(consoleSpy).toHaveBeenCalledWith("logUnexpectedEvent called with invalid source: Invalid source.");
        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleCompressed
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleCompressed', () => {

        let e1;
        let e2;
        let e3;
        let defaultSetSpy;
        let aboutStationSpy;
        beforeEach(() => {

            // create some elements that we can compress
            e1 = document.createElement('div');
            e2 = document.createElement('div');
            e3 = document.createElement('div');
            workingSpace.appendChild(e1);
            workingSpace.appendChild(e2);
            workingSpace.appendChild(e3);

            // mock applyDisplayStyleCompressedDefaultSet that returns e1 and e2
            defaultSetSpy = spyOn(this, 'applyDisplayStyleCompressedDefaultSet').and.returnValue([ e1, e2 ]);

            // mock applyDisplayStyleCompressedAboutStation that does nothing
            aboutStationSpy = spyOn(this, 'applyDisplayStyleCompressedAboutStation');

        });

        it('compresses (only) the default set', () => {

            // mock getComponentKey that returns a key with the default behaviour
            spyOn(this, 'getComponentKey').and.returnValue('genericComponent');

            // compress the default set (e1 and e2)
            applyDisplayStyleCompressed(workingSpace, null, true);
            expect(e1.style.display).toBe('none');
            expect(e2.style.display).toBe('none');
            expect(e3.style.display).toBe('');

            // uncompress
            applyDisplayStyleCompressed(workingSpace, null, false);
            expect(e1.style.display).toBe('');
            expect(e2.style.display).toBe('');
            expect(e3.style.display).toBe('');

        });

        it('invokes special case for aboutStation', () => {

            // mock getComponentKey that returns 'aboutStation'
            const componentKeySpy = spyOn(this, 'getComponentKey').and.returnValue('aboutStation');

            // check that the aboutStation case is involed with the default set (e1 and e2)
            applyDisplayStyleCompressed(workingSpace, null, true);
            expect(aboutStationSpy).toHaveBeenCalledWith([e1, e2]);

        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleCompressedAboutStation
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleCompressedAboutStation', () => {

        let e1;
        let e2;
        let morePastWeather;
        let pastWeatherBody;
        let pastWeatherButtons;
        let unexpectedEventSpy;
        beforeEach(() => {

            // mock some elements that aren't part of the About Station component
            e1 = document.createElement('div');
            e2 = document.createElement('div');
            workingSpace.appendChild(e1);
            workingSpace.appendChild(e2);

            // mock the About Station component
            morePastWeather = document.createElement('div');
            morePastWeather.classList.add('past-bom-component-container-3-1-C25_CTA');
            pastWeatherBody = document.createElement('div');
            pastWeatherBody.classList.add('bom-body');
            morePastWeather.appendChild(pastWeatherBody);
            pastWeatherButtons = document.createElement('div');
            pastWeatherButtons.classList.add('cta-module__button-container');
            morePastWeather.appendChild(pastWeatherButtons);
            workingSpace.appendChild(morePastWeather);

            // spy on expected events
            unexpectedEventSpy = spyOn(window, 'logUnexpectedEvent');

        });

        it('removes the "more past weather container" and adds its body and buttons', () => {

            // mock elements to compress
            let elementsToCompress = [ e1, morePastWeather, e2 ];

            // verify that morePastWeather is replaced by the body and buttons (at the end of the list)
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ e1, e2, pastWeatherBody, pastWeatherButtons ]);
            expect(unexpectedEventSpy).not.toHaveBeenCalled();
        });

        it('logs an unexpected event when the "more past weather" container is found but the body is missing', () => {

            // if the body is missing, morePastWeather is still removed from list, but the buttons are added
            pastWeatherBody.remove();
            let elementsToCompress = [ morePastWeather ];
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ pastWeatherButtons]);
            expect(unexpectedEventSpy).toHaveBeenCalledWith('dom', jasmine.any(String));

        });

        it('logs an unexpected event when the "more past weather" container is found but missing buttons', () => {

            // if the buttons are missing, morePastWeather is still removed from list, but the body is added
            pastWeatherButtons.remove();
            let elementsToCompress = [ morePastWeather ];
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ pastWeatherBody ]);
            expect(unexpectedEventSpy).toHaveBeenCalledWith('dom', jasmine.any(String));

        });

        it('logs an unexpected event when the "more past weather" container is missing', () => {

            let elementsToCompress = [ e1 ];
            applyDisplayStyleCompressedAboutStation(elementsToCompress);
            expect(elementsToCompress).toEqual([ e1 ]);
            expect(unexpectedEventSpy).toHaveBeenCalledWith("dom", jasmine.any(String));
        });

    });


    ///////////////////////////////////////////////////////////////////////////
    // applyDisplayStyleCompressedAboutStation
    //
    ///////////////////////////////////////////////////////////////////////////
    describe('applyDisplayStyleCompressedDefaultSet', () => {

        let root;
        let titleArea;
        beforeEach(() => {

            // create a root element
            root = document.createElement('div');
            workingSpace.appendChild(root);

            // create a title area put don't insert it into the tree yet
            titleArea = document.createElement('div');
        });

        it('returns the root when no title area exists', () => {

            const set = applyDisplayStyleCompressedDefaultSet(root, null);
            expect(set).toEqual([ root ]);

        });

        it('returns nothing when the root is the title area', () => {

            const set = applyDisplayStyleCompressedDefaultSet(root, root);
            expect(set).toEqual([]);

        });

        it('returns nothing when there are no paths other than the title area', () => {

            // root element with single title area as child
            root.appendChild(titleArea);
            const set1 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set1).toEqual([]);

            // root element with single path to title area
            const e1 = document.createElement('div');
            root.appendChild(e1);
            e1.appendChild(titleArea);
            const set2 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set2).toEqual([]);

        });

        it('returns non-ancestors of the title area', () => {

            // other elements at the same level as the title area
            const e1 = document.createElement('div');
            const e2 = document.createElement('div');
            root.appendChild(e1);
            root.appendChild(titleArea);
            root.appendChild(e2);
            const set1 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set1).toEqual([ e1, e2 ]);

            // other elements at the same level as the title area's parent
            e1.appendChild(titleArea);
            const set2 = applyDisplayStyleCompressedDefaultSet(root, titleArea);
            expect(set2).toEqual([ e2 ]);

        });

    });

});