///////////////////////////////////////////////////////////////////////////////
// Unit tests for Microsoft Office365 scripts, partially generated by Github
// Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// moveapprail.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('moveapprail.js functions', () => {

    let workingSpace;
    let observerSpy;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {
        // clear persistent values
        GM_clearValues();

        // clear the app rail collection
        appRailCollection = [ ];
        appRailSeparator = 0;

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);
        
        // app launcher
        const appLauncher = document.createElement('div');
        appLauncher.id = 'O365_MainLink_NavMenu';
        workingSpace.appendChild(appLauncher);

        // header buttons
        const headerButtonsRegion = document.createElement('div');
        headerButtonsRegion.id = 'headerButtonsRegionId';
        headerButtonsRegion.style.display = 'flex';
        workingSpace.appendChild(headerButtonsRegion);
        const button1 = document.createElement('div');
        const button2 = document.createElement('div');
        button1.className = 'mockHeaderButton';
        button2.className = 'mockHeaderButton';
        headerButtonsRegion.appendChild(button1);
        headerButtonsRegion.appendChild(button2);

        // left rail
        const leftRail = document.createElement('div');
        leftRail.id = 'LeftRail';
        workingSpace.appendChild(leftRail);

        // the first section of the left rail contains the apps
        const leftRailSection1 = document.createElement('div');
        leftRailSection1.className = '___1w2h5wn';
        leftRail.appendChild(leftRailSection1);
        const app1 = document.createElement('div');
        app1.className = '___77lcry0';
        app1.id = 'a1';
        const app2 = document.createElement('div');
        app2.className = '___77lcry0';
        app2.id = 'a2';
        leftRailSection1.appendChild(app1);
        leftRailSection1.appendChild(app2);

        // the second section of the left rail contains the More Apps widget
        const leftRailSection2 = document.createElement('div');
        leftRailSection2.className = '___1fkhojs';
        leftRail.appendChild(leftRailSection2);
        const moreApps = document.createElement('div');
        moreApps.className = '___77lcry0';
        moreApps.id = 'moreApps';
        leftRailSection2.appendChild(moreApps);

        // main module
        const mainModule = document.createElement('div');
        mainModule.id = 'MainModule';
        workingSpace.appendChild(mainModule);

        // spy for tracking observers
        observerSpy = spyOn(MutationObserver.prototype, 'observe').and.callThrough();
    });

    afterEach(() => {
        // remove the working space and spy
        document.body.removeChild(workingSpace);
        observerSpy.and.callThrough();
    });


    // test response to page rebuilding
    it('onDocumentMutation', () => {

        // trigger a page rebuild event
        const leftRail = document.getElementById("LeftRail");
        const mainModule = document.getElementById("MainModule");
        onDocumentMutation([{ addedNodes: [leftRail, mainModule] }]);
    
        // the default leftRail is draggable and unhidden 
        expect(leftRail.draggable).toBeTrue();
        expect(leftRail.style.display).toBe('');

        // verify that mainModule is under observation
        expect(observerSpy).toHaveBeenCalledWith( mainModule,
            { childList: true, subtree: true, attributes: false, characterData: false }
        );

        // move the rail to the header; the left rail should no longer be visible
        setAppRailPosition('header');
        onDocumentMutation([{ addedNodes: [leftRail, mainModule] }]);
        expect(leftRail.style.display).toBe('none');

    });

    it('onMainModuleMutation', () => {

        // mock up the mail screen
        mockMailScreen(workingSpace);

        // check each position of the app rail
        for (const pos of [ 'default', 'header', 'footer', 'none' ]) {
            // move the app rail to the new position
            setAppRailPosition(pos);
            onMainModuleMutation(null, null);

            if (pos !== 'none') {
                // check that the app rail is displayed and draggable
                const appRailRegion = getAppRailRegion();
                expect(appRailRegion.style.display).toBe('flex');
                expect(appRailRegion.draggable).toBeTrue(); // but is false when pos === footer

                // check that the app rail contains the two sections set up in beforeEach()
                let numberRailApp1 = 0;
                let numberRailApp2 = 0;
                let numberHeaderButtons = 0;
                let railChild = appRailRegion.firstElementChild;
                while (railChild != null) {
                    if (railChild.className === '___1w2h5wn') {
                        numberRailApp1++;
                    } else if (railChild.className === '___1fkhojs') {
                        numberRailApp2++;
                    } else if (railChild.className === 'mockHeaderButton') {
                        numberHeaderButtons++;
                    } else {
                        fail('Unexpected app rail element with class \'' + railChild.className + '\'');
                    }
                    railChild = railChild.nextElementSibling;
                }
                expect(numberRailApp1).toBe(1);
                expect(numberRailApp2).toBe(1);
                expect(numberHeaderButtons).toBe(pos === 'header' ? 2 : 0)
            }

            // check that unused regions aren't displayed
            const headerButtonsRegion = document.getElementById('headerButtonsRegionId');
            const leftRail = document.getElementById('LeftRail');
            const bottomRail = document.getElementById('bottomRail');
            if (pos !== 'default') {
                expect(leftRail.style.display).toBe('none');
            }
            if (bottomRail != null && pos !== 'footer') {
                expect(bottomRail.style.display).toBe('none');
            }
            // the header is always displayed
            expect(headerButtonsRegion.style.display).toBe('flex');

            // check header buttons
            if (pos !== 'header') {
                let numberButtons = 0;
                let headerButton = headerButtonsRegion.firstElementChild;
                while (headerButton != null) {
                    if (headerButton.className !== '___1w2h5wn' && headerButton.className !== '___1fkhojs') {
                        expect(headerButton.className).toBe('mockHeaderButton');
                        numberButtons++;
                    }
                    headerButton = headerButton.nextElementSibling;
                }
                expect(numberButtons).toBe(2);
            }

        }
    });

    
    it('fetchBottomRail (mail screen)', () => {

        // mock up the mail screen
        mockMailScreen(workingSpace);

        // check that fetchBottomRail(false) returns no bottom rail
        expect(fetchBottomRail(false)).toBeNull();
 
        // check that the bottom rail is created with all the correct properties
        const bottomRail = fetchBottomRail(true);
        expect(bottomRail).toBeTruthy();
        expect(bottomRail.id).toBe('bottomRail');
        expect(bottomRail.style.display).toBe('flex');
        expect(document.body.querySelector('#bottomRail')).toBe(bottomRail);

        // check that a second call to fetchBottomRail returns the bottom rail created earlier
        expect(fetchBottomRail(false)).toBe(bottomRail);
        expect(fetchBottomRail(true)).toBe(bottomRail);

    });
    
    
    it('fetchBottomRail (calendar screen)', () => {

        // set up the calendar screen
        mockCalendarScreen(workingSpace);
 
        // check that the bottom rail is created with all the correct properties
        const bottomRail = fetchBottomRail(true);
        expect(bottomRail).toBeTruthy();
        expect(bottomRail.id).toBe('bottomRail');
        expect(bottomRail.style.display).toBe('flex');
        expect(document.body.querySelector('#bottomRail')).toBe(bottomRail);

        // check that a second call to fetchBottomRail returns the bottom rail created earlier
        expect(fetchBottomRail(false)).toBe(bottomRail);
        expect(fetchBottomRail(true)).toBe(bottomRail);

    });


    it('findAppLauncher', () => {
        const appLauncher = findAppLauncher();
        expect(appLauncher.id).toBe('O365_MainLink_NavMenu');
    });


    it('findHeaderButtonsRegion', () => {
        const headerButtonsRegion = findHeaderButtonsRegion();
        expect(headerButtonsRegion.id).toBe('headerButtonsRegionId');
    });


    it('findLeftPanel (mail screen)', () => {
        mockMailScreen(workingSpace);
        const leftPanel = findLeftPanel()
        expect(leftPanel.id).toBe('folderPaneDroppableContainer');
    });


    it('findLeftPanel (calendar screen)', () => {
        mockCalendarScreen(workingSpace);
        const leftPanel = findLeftPanel();
        expect(leftPanel.className).toBe('SFJ5T');
        expect(leftPanel.firstElementChild.className).toBe('AMOVa');
    });


    it('getAppRailPosition/setAppRailPosition', () => {

        // check the default position
        expect(getAppRailPosition()).toBe(appRailConf);

        // check valid values for appRailPosition
        for (const pos of [ 'default', 'header', 'footer', 'none' ]) {
            setAppRailPosition(pos);
            expect(GM_getValue('appRailPosition', null)).toBe(pos);
            expect(getAppRailPosition()).toBe(pos);
        }

        // check that an invalid value is rejected
        const oldValue = getAppRailPosition();
        setAppRailPosition('invalid');
        expect(getAppRailPosition()).toBe(oldValue);

    });


    it('getAppRailRegion', () => {
        // header: return headerButtonsRegion
        setAppRailPosition('header');
        expect(getAppRailRegion().id).toBe('headerButtonsRegionId');

        // footer: creates bottomRail via fetchBottomRail; ensure left panel exists
        mockMailScreen(workingSpace);
        setAppRailPosition('footer');
        expect(getAppRailRegion().id).toBe('bottomRail');

        // none: returns null
        setAppRailPosition('none');
        expect(getAppRailRegion()).toBeNull();

        // default: returns element with id LeftRail
        setAppRailPosition('default');
        expect(getAppRailRegion().id).toBe('LeftRail');
    });

    it('makeDragDropRail', () => {

        // draggingAppRail starts false
        expect(draggingAppRail).toBe(false);

        // make a draggable element
        const e = document.createElement('div');
        workingSpace.appendChild(e);
        makeDragDropRail(e, true);
        expect(e.draggable).toBe(true);

        // check that starting a drag sets draggingAppRail true
        const dragStartEvent = new window.Event('dragstart', { bubbles: true, cancelable: true });
        e.dispatchEvent(dragStartEvent);
        expect(draggingAppRail).toBe(true);

        // check that default actions are prevented when draggingAppRail is true
        const dragOverEvent = new window.Event('dragover', { bubbles: true, cancelable: true });
        e.dispatchEvent(dragOverEvent);
        expect(dragOverEvent.defaultPrevented).toBe(true);

    });


    it('onDropRail', () => {
        // mock up the mail screen
        mockMailScreen(workingSpace);

        // dropping into the header
        draggingAppRail = true;
        const headerButtonsRegion = findHeaderButtonsRegion();
        const headerChild = document.createElement('div');
        headerButtonsRegion.appendChild(headerChild);
        const headerEvent = { target: headerChild, preventDefault: () => { headerEvent._p = true; } };
        onDropRail(headerEvent);
        expect(getAppRailPosition()).toBe('header');
        expect(draggingAppRail).toBe(false);

        // dropping into the left panel
        draggingAppRail = true;
        const leftPanel = findLeftPanel();
        const leftPanelChild = document.createElement('div');
        leftPanel.appendChild(leftPanelChild);
        const leftPanelEvent = { target: leftPanelChild, preventDefault: () => { leftPanelEvent._p = true; } };
        onDropRail(leftPanelEvent);
        expect(getAppRailPosition()).toBe('footer');
        expect(draggingAppRail).toBe(false);

        // dragging the app rail into the app launcher removes the rail
        draggingAppRail = true;
        setAppRailPosition('default');
        const appLauncher = findAppLauncher();
        const launcherChild = document.createElement('div');
        appLauncher.appendChild(launcherChild);
        const launcherEvent = { target: launcherChild, preventDefault: () => { launcherEvent._p = true; } };
        onDropRail(launcherEvent);
        expect(getAppRailPosition()).toBe('none');

        // dragging the app launcher out restores the rail
        draggingAppRail = true;
        setAppRailPosition('none');
        onDropRail(leftPanelEvent);
        expect(getAppRailPosition()).toBe('footer');

    });


    it('fetchAppRailCollection', () => {

        // as set up in beforeEach(), the app rail should have two apps in the first section and one in the second
        const appRailCollection = fetchAppRailCollection();
        expect(appRailCollection.length).toBe(3);
        expect(appRailSeparator).toBe(2);

    });


    it('insertAppRail', () => {

        function expectAppRailComponents(section1, section2) {
            // check the structure that has been set up in beforeEach()
            expect(section1.className).toBe('___1w2h5wn');
            expect(section2.className).toBe('___1fkhojs');
            expect(section1.children.length).toBe(2);
            expect(section2.children.length).toBe(1);
            expect(section1.children.item(0).id).toBe('a1');
            expect(section1.children.item(1).id).toBe('a2');
            expect(section2.children.item(0).id).toBe('moreApps');
        }

        // insert the app rail into an empty region
        const emptyTarget = document.createElement('div');
        workingSpace.appendChild(emptyTarget);
        insertAppRail(emptyTarget);

        // check that the app rail contains the two sections set up in beforeEach()
        expect(emptyTarget.children.length).toBe(2);
        expectAppRailComponents(emptyTarget.children.item(0), emptyTarget.children.item(1));

        // insert the app rail into a region with an existing button
        const occupiedTarget = document.createElement('div');
        workingSpace.appendChild(occupiedTarget);
        const existingButton = document.createElement('div');
        existingButton.className = 'existingButton';
        occupiedTarget.appendChild(existingButton);
        insertAppRail(occupiedTarget);

        // check that the app rail contains the existing button plus two sections set up in beforeEach()
        expect(occupiedTarget.children.length).toBe(3);
        expect(occupiedTarget.children.item(0).className).toBe('existingButton');
        expectAppRailComponents(occupiedTarget.children.item(1), occupiedTarget.children.item(2));

    });


    it('removeHeaderButtons/restoreHeaderButtons', () => {

        const headerButtonsRegion = findHeaderButtonsRegion();

        // child that should be removed (in headerButtonsConf and set false)
        const button1 = document.createElement('div');
        button1.id = 'owaMeetNowButton_container';
        headerButtonsRegion.appendChild(button1);

        // child that should remain
        const button2 = document.createElement('div');
        button2.id = 'owaSettingsBtn_container';
        headerButtonsRegion.appendChild(button2);

        // child that looks like an app rail button
        const button3 = document.createElement('div');
        button3.className = '___77lcry0';
        headerButtonsRegion.appendChild(button3);

        // clear headerButtonsCollection
        headerButtonsCollection = [];

        // check removeHeaderButtons moves button1 into headerButtonsCollection and removes button3 entirely
        removeHeaderButtons();
        expect(headerButtonsCollection.find(x => x.id === 'owaMeetNowButton_container')).toBeTruthy();
        expect(headerButtonsRegion.querySelector('.___77lcry0')).toBeNull();

        // restore buttons and check that button1 returns
        restoreHeaderButtons();
        expect(headerButtonsRegion.querySelector('#owaMeetNowButton_container')).toBeTruthy();
  });

});


// mock up the calendar screen
function mockCalendarScreen(root) {

    // create divs with classes SFj5T and AMOVa to simulate the calendar area
    const div1 = document.createElement('div');
    div1.className = 'SFJ5T';
    root.appendChild(div1);
    const div2 = document.createElement('div');
    div2.className = 'AMOVa';
    div1.appendChild(div2);

}


// mock up the mail screen
function mockMailScreen(root) {

    const folderPane = document.createElement('div');
    folderPane.id = 'folderPaneDroppableContainer';
    root.appendChild(folderPane);

}


///////////////////////////////////////////////////////////////////////////////
// texteditorstatusbar.js tests
//
///////////////////////////////////////////////////////////////////////////////
describe('texteditorstatusbar.js', () => {

    let workingSpace;

    beforeEach(() => {
        // clear persistent values
        GM_clearValues();
        
        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);

        // mock up the title bar
        // (individual tests may update with mockSimpleTitleBar() and mockComplexTitleBar())
        const titleBarContainer = document.createElement('div');
        titleBarContainer.id = 'TitleBar';
        workingSpace.appendChild(titleBarContainer);
        mockSimpleTitleBar();

        // mock up some margin with view lines
        const margin = document.createElement('div');
        margin.className = 'margin';
        workingSpace.appendChild(margin);
        const marginViewOverlays = document.createElement('div');
        marginViewOverlays.className = 'margin-view-overlays';
        margin.appendChild(marginViewOverlays);
        const marginViewLines = [
            document.createElement('div'),
            document.createElement('div'),
            document.createElement('div'),
            document.createElement('div'),
            document.createElement('div')
        ];
        marginViewLines[0].textContent = '1';
        marginViewLines[1].textContent = '';    // testing text wrapped from line above
        marginViewLines[2].textContent = '2';
        marginViewLines[3].textContent = '4';   // testing out-of-order line
        marginViewLines[4].textContent = '3';
        marginViewLines[0].style.top = '0px';
        marginViewLines[1].style.top = '20px';
        marginViewLines[2].style.top = '40px';
        marginViewLines[3].style.top = '80px';
        marginViewLines[4].style.top = '60px';
        for (const marginViewLine of marginViewLines) {
            marginViewOverlays.appendChild(marginViewLine);
        }

        // mock up the viewing area
        const viewLines = document.createElement('div');
        viewLines.className = 'view-lines';
        viewLines.style.fontSize = '14px';
        workingSpace.appendChild(viewLines);

        // mock up the cursor
        const cursorsLayer = document.createElement('div');
        cursorsLayer.className = 'cursors-layer';
        workingSpace.appendChild(cursorsLayer);
        const cursor = document.createElement('div');
        cursor.className = 'cursor';
        cursorsLayer.appendChild(cursor);
    });

    afterEach(() => {
        // remove the working space
        document.body.removeChild(workingSpace);
    });

    it('fetchStatusBar', () => {

        const statusBar = fetchStatusBar();
        const statusBarClassName = getStatusBarClassName();

        // check there exists exactly three spans with class statusBarClassName
        expect(statusBar.length).toBe(3);
        expect(document.getElementsByClassName(statusBarClassName).length).toBe(statusBar.length);
        for (const element of statusBar) {
            expect(element.tagName).toBe('SPAN');
            expect(element.className).toBe(statusBarClassName);
        }

        // check that the suggestions button section contains a button
        const suggestButtonIndex = 2;
        expect(statusBar[suggestButtonIndex].firstElementChild.tagName).toBe('BUTTON');

    });

    it('getCursorPositionLabel', () => {
        expect(getCursorPositionLabel(1, 1)).toBe('Line: 1 Column: 1');
        expect(getCursorPositionLabel(5, 10)).toBe('Line: 5 Column: 10');
    });


    it('getSuggestionsButtonLabel', () => {
        expect(getSuggestionsButtonLabel(true)).toBe('Suggestions: On');
        expect(getSuggestionsButtonLabel(false)).toBe('Suggestions: Off');
    });

    it('getColumnNumberForHorizontalOffset', () => {
        // font size 14px gives 8.43 pixels per character in a monospace font
        // getColumnNumber rounds the column number up, so 0 = column 1, 0.5 of a character = column 2, etc.
        expect(getColumnNumberForHorizontalOffset(0)).toBe(1);
        expect(getColumnNumberForHorizontalOffset(1)).toBe(2);
        expect(getColumnNumberForHorizontalOffset(15)).toBe(3);
        expect(getColumnNumberForHorizontalOffset(665)).toBe(80);
    });

    it('getLineNumberForVerticalOffset', () => {
        // valid offsets
        expect(getLineNumberForVerticalOffset(0)).toBe(1);
        expect(getLineNumberForVerticalOffset(20)).toBe(1); // wrapped from line above
        expect(getLineNumberForVerticalOffset(40)).toBe(2);
        expect(getLineNumberForVerticalOffset(59)).toBe(2);
        expect(getLineNumberForVerticalOffset(60)).toBe(3);
        expect(getLineNumberForVerticalOffset(80)).toBe(4);

        // invalid offsets return NaN
        expect(isNaN(getLineNumberForVerticalOffset(-1))).toBeTrue();
        expect(isNaN(getLineNumberForVerticalOffset(100))).toBeTrue();
    });

    it('getStatusBarClassName', () => {

        // in the simplest case, the status bar has class od-OneUpTextFile-status
        mockSimpleTitleBar();
        expect(getStatusBarClassName()).toBe('od-OneUpTextFile-status');

        // in the complex case, the status bar has class OneUpTextFileStatus_xxxxxxxx
        const nonce = getHexNonce(8);
        mockComplexTitleBar(nonce);
        expect(getStatusBarClassName()).toBe('OneUpTextFileStatus_' + nonce);
    });

    it('getTitleBar', () => {

        // in the simplest case, the title bar has class od-OneUpTextFile-title
        mockSimpleTitleBar();
        let titleBar = getTitleBar();
        expect(titleBar.className).toBe('od-OneUpTextFile-title');

        // in the complex case, the title bar has class OneUpTextFileTitle_xxxxxxxx
        const nonce = getHexNonce(8);
        mockComplexTitleBar(nonce);
        titleBar = getTitleBar();
        expect(titleBar.className).toBe('OneUpTextFileTitle_' + nonce);

    });

    it('onCursorsLayerMutation', () => {

        // build the title bar and status bar
        const statusBar = fetchStatusBar();
        const cursorIndex = 2;

        // cursor starts at pixels (0, 0) and characters (1, 1)
        expect(lastCursorPosition.top).toBe(0);
        expect(lastCursorPosition.left).toBe(0);
        expect(lastCursorPosition.line).toBe(1);
        expect(lastCursorPosition.column).toBe(1);

        // simulate moving the cursor to pixels (20, 30)
        let cursor = workingSpace.querySelector(".cursors-layer > .cursor");
        cursor.style.top = '20px';
        cursor.style.left = '30px';
        onCursorsLayerMutation([], cursorIndex);
        expect(lastCursorPosition.top).toBe(20);
        expect(lastCursorPosition.left).toBe(30);
        expect(lastCursorPosition.line).toBe(getLineNumberForVerticalOffset(20));
        expect(lastCursorPosition.column).toBe(getColumnNumberForHorizontalOffset(30));
        expect(statusBar[cursorIndex].textContent).toBe(getCursorPositionLabel(
            getLineNumberForVerticalOffset(20),
            getColumnNumberForHorizontalOffset(30)
        ));

        // simulate scrolling the cursor outside the display area (the line number should be unchanged)
        cursor.style.top = '100px';
        cursor.style.left = '0px';
        onCursorsLayerMutation([], cursorIndex);
        expect(lastCursorPosition.top).toBe(100);
        expect(lastCursorPosition.left).toBe(0);
        expect(lastCursorPosition.line).toBe(getLineNumberForVerticalOffset(20));
        expect(lastCursorPosition.column).toBe(getColumnNumberForHorizontalOffset(0));
        expect(statusBar[cursorIndex].textContent).toBe(getCursorPositionLabel(
            getLineNumberForVerticalOffset(20),
            getColumnNumberForHorizontalOffset(0)
        ));

    });

    it('onStatusBarSuggestClick', () => {

        // construct the status bar
        const statusBar = fetchStatusBar();
        const suggestButtonIndex = 2;
        const suggestButton = statusBar[suggestButtonIndex].querySelector('button');

        // default showSuggestWidget value is true
        showSuggestWidget = true;
        expect(suggestButton.textContent).toBe(getSuggestionsButtonLabel(true));

        // clicking the suggestions button changes the value to false
        onStatusBarSuggestClick(suggestButtonIndex);
        expect(showSuggestWidget).toBeFalse();
        expect(GM_getValue('showSuggestWidget', null)).toBeFalse();
        expect(suggestButton.textContent).toBe(getSuggestionsButtonLabel(false));

        // clicking again returns the value to true
        onStatusBarSuggestClick(suggestButtonIndex);
        expect(showSuggestWidget).toBeTrue();
        expect(GM_getValue('showSuggestWidget', null)).toBeTrue();
        expect(suggestButton.textContent).toBe(getSuggestionsButtonLabel(true));

    });

    it('onSuggestWidgetMutation', () => {

        // mock up a mutation observer that does nothing
        const observer = new MockMutationObserver(() => {});

        // mock suggestions widget
        const suggestionsWidget = document.createElement('div');
        suggestionsWidget.className = 'suggest-widget';
        workingSpace.appendChild(suggestionsWidget);

        // with showSuggestWidget true, mutation of the class attribute causes the suggestions widget to display
        showSuggestWidget = true;
        const classMutations = [ { target: suggestionsWidget, attributeName: 'class' } ];
        onSuggestWidgetMutation(classMutations, observer);
        expect(suggestionsWidget.style.display).toBe('');

        // with showSuggestWidget false, mutation of the class attribute suppresses the suggestions widget
        showSuggestWidget = false;
        onSuggestWidgetMutation(classMutations, observer);
        expect(suggestionsWidget.style.display).toBe('none');

        // other mutations don't change the display state
        showSuggestWidget = true;
        const nonClassMutations = [ { target: suggestionsWidget, attributeName: 'style' } ];
        onSuggestWidgetMutation(nonClassMutations, observer);
        expect(suggestionsWidget.style.display).toBe('none');

    });

});


// get a nonce for simulating hex digits appended to class names
function getHexNonce(length) {

    const hexDigits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'];
    let nonce = '';
    for (let i = 0; i < length; i++) {
        nonce += hexDigits[Math.floor(Math.random() * 16)];
    }

    return nonce;
}


// mock up the simple version of the title bar
function mockSimpleTitleBar() {

    // clear the cached status bar class name
    statusBarClassName = null;

    // clear any existing title bar
    const titleBarContainer = document.getElementById('TitleBar');
    titleBarContainer.innerHTML = '';

    // the simple title bar is a div with class od-OneUpTextFile-title
    const titleBar = document.createElement('div');
    titleBar.className = 'od-OneUpTextFile-title';
    titleBarContainer.appendChild(titleBar);

}


// mock up the complex version of the title bar
function mockComplexTitleBar(titleBarNonce) {

    // clear the cached status bar class name
    statusBarClassName = null;

    // clear any existing title bar
    const titleBarContainer = document.getElementById('TitleBar');
    titleBarContainer.innerHTML = '';

    // the complex title bar is a div with class OneUpTextFileTitle_xxxxxxxx,
    // which is child of OneUpTextFileContent_xxxxxxxx
    const textFileContent = document.createElement('div');
    textFileContent.className = 'OneUpTextFileContent_' + titleBarNonce;
    titleBarContainer.appendChild(textFileContent);
    titleBar = document.createElement('div');
    titleBar.className = 'OneUpTextFileTitle_' + titleBarNonce;
    textFileContent.appendChild(titleBar);

    // finding the title bar requires a descendent with a ficed class name oneUpTextEditor
    const textEditorParent = document.createElement('div');
    textFileContent.appendChild(textEditorParent);
    const textEditor = document.createElement('div');
    textEditor.className = 'oneUpTextEditor';
    textEditorParent.appendChild(textEditor);

}
