///////////////////////////////////////////////////////////////////////////////
// Unit tests for Microsoft Office365 scripts, partially generated by Github
// Copilot.
//
// Copyright (c) 2026 Nicholas Paul Sheppard. See README.md for details
//
// Buy me a Ko-Fi at https://ko-fi.com/npsheppard.
///////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////
// moveapprail.js tests
//
//////////////////////////////////////////////////////////////////////////////
describe('moveapprail.js functions', () => {

    let workingSpace;

    // before each test, create a skeleton of the page, containing only the components we want to test
    beforeEach(() => {
        // clear the persistent values
        GM_clearValues();

        // create working space that will be reset at the end of each test
        workingSpace = document.createElement('div');
        document.body.appendChild(workingSpace);
        
        // app launcher
        const appLauncher = document.createElement('div');
        appLauncher.id = 'O365_MainLink_NavMenu';
        workingSpace.appendChild(appLauncher);

        // header buttons region
        const headerButtonsRegion = document.createElement('div');
        headerButtonsRegion.id = 'headerButtonsRegionId';
        workingSpace.appendChild(headerButtonsRegion);

        // left rail
        const leftRail = document.createElement('div');
        leftRail.id = 'LeftRail';
        workingSpace.appendChild(leftRail);
        const leftRailSection1 = document.createElement('div');
        leftRailSection1.className = '___1w2h5wn';
        leftRail.appendChild(leftRailSection1);
        const leftRailSection2 = document.createElement('div');
        leftRailSection2.className = '___1fkhojs';
        leftRail.appendChild(leftRailSection2);
        const app1 = document.createElement('div');
        app1.className = '___77lcry0';
        app1.id = 'a1';
        const app2 = document.createElement('div');
        app2.className = '___77lcry0';
        app2.id = 'a2';
        leftRailSection1.appendChild(app1);
        leftRailSection2.appendChild(app2);

        // main module
        const mainModule = document.createElement('div');
        mainModule.id = 'MainModule';
        workingSpace.appendChild(mainModule);
    });
  
    afterEach(() => {
        // remove the working space
        document.body.removeChild(workingSpace);
    });
  
    // test response to page rebuilding
    it('onDocumentMutation', () => {

        // trigger a page rebuild event; TODO: test rebuilds with the leftRail in different positions
        const leftRail = document.getElementById("LeftRail");
        const mainModule = document.getElementById("MainModule");
        onDocumentMutation([{ addedNodes: [leftRail, mainModule] }]);
    
        // the default leftRail is draggable and unhidden 
        expect(leftRail.draggable).toBe(true);
        expect(leftRail.style.display).toBe('');

        // TODO: verify that observers have been created
    });
    
    
    it('fetchBottomRail appends the bottom rail to the mail screen', () => {

        // set up the mail screen
        simulateMailScreen(workingSpace);
 
        // check that the bottom rail is created with all the correct properties
        const bottomRail = fetchBottomRail();
        expect(bottomRail).toBeTruthy();
        expect(bottomRail.id).toBe('bottomRail');
        expect(bottomRail.style.display).toBe('flex');
        expect(document.body.querySelector('#bottomRail')).toBe(bottomRail);

        // check that a second call to fetchBottomRail returns the bottom rail created earlier
        expect(fetchBottomRail()).toBe(bottomRail);

    });
    
    
    it('fetchBottomRail appends the bottom rail to the calendar screen', () => {

        // set up the calendar screen
        simulateCalendarScreen(workingSpace);
 
        // check that the bottom rail is created with all the correct properties
        const bottomRail = fetchBottomRail();
        expect(bottomRail).toBeTruthy();
        expect(bottomRail.id).toBe('bottomRail');
        expect(bottomRail.style.display).toBe('flex');
        expect(document.body.querySelector('#bottomRail')).toBe(bottomRail);

        // check that a second call to fetchBottomRail returns the bottom rail created earlier
        expect(fetchBottomRail()).toBe(bottomRail);

    });


    it('findAppLauncher returns the element with id O365_MainLink_NavMenu', () => {
        const appLauncher = findAppLauncher();
        expect(appLauncher.id).toBe('O365_MainLink_NavMenu');
    });


    it('findHeaderButtonsRegion returns the headerButtonsRegionId element', () => {
        const headerButtonsRegion = findHeaderButtonsRegion();
        expect(headerButtonsRegion.id).toBe('headerButtonsRegionId');
    });


    it('findLeftPanel returns folderPaneDroppableContainer for the mail screen', () => {
        simulateMailScreen(workingSpace);
        const leftPanel = findLeftPanel()
        expect(leftPanel.id).toBe('folderPaneDroppableContainer');
    });


    it('findLeftPanel returns .SFJ5T > .AMOva for the calendar screen', () => {
        simulateCalendarScreen(workingSpace);
        const leftPanel = findLeftPanel();
        expect(leftPanel.className).toBe('SFJ5T');
        expect(leftPanel.firstElementChild.className).toBe('AMOVa');
    });


    it('getAppRailPosoition/setAppRailPosition get/set the app rail position value', () => {

        // check the default position
        expect(getAppRailPosition()).toBe(appRailConf);

        // check valid values for appRailPosition
        for (let pos of [ 'default', 'header', 'footer', 'none' ]) {
            setAppRailPosition(pos);
            expect(GM_getValue('appRailPosition', null)).toBe(pos);
            expect(getAppRailPosition()).toBe(pos);
        }

        // check that an invalid value is rejected
        const oldValue = getAppRailPosition();
        setAppRailPosition('invalid');
        expect(getAppRailPosition()).toBe(oldValue);

    });


    it('getAppRailRegion honours app rail position setting', () => {
        // header: return headerButtonsRegion
        setAppRailPosition('header');
        expect(getAppRailRegion().id).toBe('headerButtonsRegionId');

        // footer: creates bottomRail via fetchBottomRail; ensure left panel exists
        simulateMailScreen(workingSpace);
        setAppRailPosition('footer');
        expect(getAppRailRegion().id).toBe('bottomRail');

        // none: returns null
        setAppRailPosition('none');
        expect(getAppRailRegion()).toBeNull();

        // default: returns element with id LeftRail
        setAppRailPosition('default');
        expect(getAppRailRegion().id).toBe('LeftRail');
  });

    it('makeDragDropRail attaches handlers and dragstart sets draggingAppRail', () => {

        // draggingAppRail starts false
        expect(draggingAppRail).toBe(false);

        // make a draggable element
        const e = document.createElement('div');
        workingSpace.appendChild(e);
        makeDragDropRail(e, true);
        expect(e.draggable).toBe(true);

        // check that starting a drag sets draggingAppRail true
        const dragStartEvent = new window.Event('dragstart', { bubbles: true, cancelable: true });
        e.dispatchEvent(dragStartEvent);
        expect(draggingAppRail).toBe(true);

        // check that default actions are prevented when draggingAppRail is true
        const dragOverEvent = new window.Event('dragover', { bubbles: true, cancelable: true });
        e.dispatchEvent(dragOverEvent);
        expect(dragOverEvent.defaultPrevented).toBe(true);

    });


    it('onDropRail sets appRailPosition correctly for header/leftPanel/appLauncher', () => {
        // set up the mail screen
        simulateMailScreen(workingSpace);

        // dropping into header
        draggingAppRail = true;
        const headerButtonsRegion = findHeaderButtonsRegion();
        const headerChild = document.createElement('div');
        headerButtonsRegion.appendChild(headerChild);
        const headerEvent = { target: headerChild, preventDefault: () => { headerEvent._p = true; } };
        onDropRail(headerEvent);
        expect(getAppRailPosition()).toBe('header');
        expect(draggingAppRail).toBe(false);

        // dropping into leftPanel
        draggingAppRail = true;
        const leftPanel = findLeftPanel();
        const leftPanelChild = document.createElement('div');
        leftPanel.appendChild(leftPanelChild);
        const leftPanelEvent = { target: leftPanelChild, preventDefault: () => { leftPanelEvent._p = true; } };
        onDropRail(leftPanelEvent);
        expect(getAppRailPosition()).toBe('footer');
        expect(draggingAppRail).toBe(false);

        // dropping into app launcher toggles 'default' <-> 'none'
        draggingAppRail = true;
        setAppRailPosition('default');
        const appLauncher = findAppLauncher();
        const launcherChild = document.createElement('div');
        appLauncher.appendChild(launcherChild);
        const launcherEvent = { target: launcherChild, preventDefault: () => { launcherEvent._p = true; } };
        onDropRail(launcherEvent);
        expect(getAppRailPosition()).toBe('none');

        draggingAppRail = true;
        setAppRailPosition('none');
        onDropRail(launcherEvent);
        expect(getAppRailPosition()).toBe('default');

    });


    it('removeHeaderButtons moves unwanted header buttons and removes app rail buttons', () => {

        const headerButtonsRegion = findHeaderButtonsRegion();

        // child that should be removed (in headerButtonsConf and set false)
        const button1 = document.createElement('div');
        button1.id = 'owaMeetNowButton_container';
        headerButtonsRegion.appendChild(button1);

        // child that should remain
        const button2 = document.createElement('div');
        button2.id = 'owaSettingsBtn_container';
        headerButtonsRegion.appendChild(button2);

        // child that looks like an app rail button
        const button3 = document.createElement('div');
        button3.className = '___77lcry0';
        headerButtonsRegion.appendChild(button3);

        // clear headerButtonsCollection
        headerButtonsCollection = [];

        // check removeHeaderButtons moves button1 into headerButtonsCollection and removes button3 entirely
        removeHeaderButtons();
        expect(headerButtonsCollection.find(x => x.id === 'owaMeetNowButton_container')).toBeTruthy();
        expect(headerButtonsRegion.querySelector('.___77lcry0')).toBeNull();

        // restore buttons and check that button1 returns
        restoreHeaderButtons();
        expect(headerButtonsRegion.querySelector('#owaMeetNowButton_container')).toBeTruthy();
  });

});


// simulate the calendar screen
function simulateCalendarScreen(root) {

    // create divs with classes SFj5T and AMOVa to simulate the calendar area
    const div1 = document.createElement('div');
    div1.className = 'SFJ5T';
    root.appendChild(div1);
    const div2 = document.createElement('div');
    div2.className = 'AMOVa';
    div1.appendChild(div2);

}


// simulate the mail screen
function simulateMailScreen(root) {

    const folderPane = document.createElement('div');
    folderPane.id = 'folderPaneDroppableContainer';
    root.appendChild(folderPane);

}
